      SUBROUTINE LSOIBT (RES, ADDA, JAC, NEQ, Y, YDOTI, T, TOUT, ITOL,
     1  RTOL, ATOL, ITASK, ISTATE, IOPT, RWORK, LRW, IWORK, LIW, MF ) 
      EXTERNAL RES, ADDA, JAC 
      INTEGER NEQ, ITOL, ITASK, ISTATE, IOPT, LRW, IWORK, LIW, MF
      DOUBLE PRECISION Y, YDOTI, T, TOUT, RTOL, ATOL, RWORK 
      DIMENSION NEQ(1), Y(1), YDOTI(1), RTOL(1), ATOL(1), RWORK(LRW), 
     1          IWORK(LIW)
C-----------------------------------------------------------------------
C THIS IS THE MARCH 30, 1987 VERSION OF LSOIBT..
C  LIVERMORE SOLVER FOR ORDINARY DIFFERENTIAL EQUATIONS GIVEN IN
C  IMPLICIT FORM, WITH BLOCK-TRIDIAGONAL JACOBIAN TREATMENT.
C THIS VERSION IS IN DOUBLE PRECISION.
C
C LSOIBT SOLVES THE INITIAL VALUE PROBLEM FOR LINEARLY IMPLICIT
C SYSTEMS OF FIRST ORDER ODE-S,
C     A(T,Y) * DY/DT = G(T,Y) ,  WHERE A(T,Y) IS A SQUARE MATRIX,
C OR, IN COMPONENT FORM,
C     ( A   * ( DY / DT ))  + ... +  ( A     * ( DY   / DT ))  =
C        I,1      1                     I,NEQ      NEQ
C
C      =   G ( T, Y , Y ,..., Y    )   ( I = 1,...,NEQ )
C           I      1   2       NEQ
C
C IF A IS SINGULAR, THIS IS A DIFFERENTIAL-ALGEBRAIC SYSTEM.
C
C LSOIBT IS A VARIANT VERSION OF THE LSODI PACKAGE, FOR THE CASE WHERE
C THE MATRICES A, DG/DY, AND D(A*S)/DY ARE ALL BLOCK-TRIDIAGONAL.
C-----------------------------------------------------------------------
C REFERENCE..
C     ALAN C. HINDMARSH,  ODEPACK, A SYSTEMATIZED COLLECTION OF ODE
C     SOLVERS, IN SCIENTIFIC COMPUTING,  R. S. STEPLEMAN ET AL. (EDS.),
C     NORTH-HOLLAND, AMSTERDAM, 1983, PP. 55-64.
C-----------------------------------------------------------------------
C AUTHORS..   CHARLES S. KENNEY
C                FORMERLY AT..
C             NAVAL WEAPONS CENTER
C             CHINA LAKE, CA 93555
C    AND
C             JEFFREY F. PAINTER  AND
C             ALAN C. HINDMARSH
C             COMPUTING AND MATHEMATICS RESEARCH DIVISION, L-316
C             LAWRENCE LIVERMORE NATIONAL LABORATORY
C             LIVERMORE, CA 94550.
C-----------------------------------------------------------------------
C SUMMARY OF USAGE. 
C
C COMMUNICATION BETWEEN THE USER AND THE LSOIBT PACKAGE, FOR NORMAL
C SITUATIONS, IS SUMMARIZED HERE.  THIS SUMMARY DESCRIBES ONLY A SUBSET
C OF THE FULL SET OF OPTIONS AVAILABLE.  SEE THE FULL DESCRIPTION FOR 
C DETAILS, INCLUDING OPTIONAL COMMUNICATION, NONSTANDARD OPTIONS,
C AND INSTRUCTIONS FOR SPECIAL SITUATIONS.  SEE ALSO THE EXAMPLE
C PROBLEM (WITH PROGRAM AND OUTPUT) FOLLOWING THIS SUMMARY. 
C
C A. FIRST, PROVIDE A SUBROUTINE OF THE FORM..
C               SUBROUTINE RES (NEQ, T, Y, S, R, IRES)
C               DIMENSION Y(NEQ), S(NEQ), R(NEQ)
C WHICH COMPUTES THE RESIDUAL FUNCTION
C     R = G(T,Y)  -  A(T,Y) * S ,
C AS A FUNCTION OF T AND THE VECTORS Y AND S.  (S IS AN INTERNALLY
C GENERATED APPROXIMATION TO DY/DT.)  THE ARRAYS Y AND S ARE INPUTS
C TO THE RES ROUTINE AND SHOULD NOT BE ALTERED.  THE RESIDUAL
C VECTOR IS TO BE STORED IN THE ARRAY R.  THE ARGUMENT IRES SHOULD BE 
C IGNORED FOR CASUAL USE OF LSOIBT.  (FOR USES OF IRES, SEE THE
C PARAGRAPH ON RES IN THE FULL DESCRIPTION BELOW.)
C
C B. NEXT, IDENTIFY THE BLOCK STRUCTURE OF THE MATRICES A = A(T,Y) AND
C DR/DY.  LSOIBT MUST DEAL INTERNALLY WITH A LINEAR COMBINATION, P, OF
C THESE TWO MATRICES.  THE MATRIX P (HENCE BOTH A AND DR/DY) MUST HAVE
C A BLOCK-TRIDIAGONAL FORM WITH FIXED STRUCTURE PARAMETERS
C     MB = BLOCK SIZE, MB .GE. 1, AND
C     NB = NUMBER OF BLOCKS IN EACH DIRECTION, NB .GE. 4,
C WITH MB*NB = NEQ.  IN EACH OF THE NB BLOCK-ROWS OF THE MATRIX P
C (EACH CONSISTING OF MB CONSECUTIVE ROWS), THE NONZERO ELEMENTS ARE
C TO LIE IN THREE CONSECUTIVE MB BY MB BLOCKS.  IN BLOCK-ROWS
C 2 THROUGH NB - 1, THESE ARE CENTERED ABOUT THE MAIN DIAGONAL.
C IN BLOCK-ROWS 1 AND NB, THEY ARE THE DIAGONAL BLOCKS AND THE TWO
C BLOCKS ADJACENT TO THE DIAGONAL BLOCK.  (THUS BLOCK POSITIONS (1,3) 
C AND (NB,NB-2) CAN BE NONZERO.)
C ALTERNATIVELY, P (HENCE A AND DR/DY) MAY BE ONLY APPROXIMATELY
C EQUAL TO MATRICES WITH THIS FORM, AND LSOIBT SHOULD STILL SUCCEED.
C THE BLOCK-TRIDIAGONAL MATRIX P IS DESCRIBED BY THREE ARRAYS,
C EACH OF SIZE MB BY MB BY NB..
C     PA = ARRAY OF DIAGONAL BLOCKS,
C     PB = ARRAY OF SUPERDIAGONAL (AND ONE SUBDIAGONAL) BLOCKS, AND
C     PC = ARRAY OF SUBDIAGONAL (AND ONE SUPERDIAGONAL) BLOCKS.
C SPECIFICALLY, THE THREE MB BY MB BLOCKS IN THE K-TH BLOCK-ROW OF P
C ARE STORED IN (READING ACROSS)..
C     PC(*,*,K) = BLOCK TO THE LEFT OF THE DIAGONAL BLOCK,
C     PA(*,*,K) = DIAGONAL BLOCK, AND
C     PB(*,*,K) = BLOCK TO THE RIGHT OF THE DIAGONAL BLOCK, 
C EXCEPT FOR K = 1, WHERE THE THREE BLOCKS (READING ACROSS) ARE
C     PA(*,*,1) (= DIAGONAL BLOCK), PB(*,*,1), AND PC(*,*,1),
C AND K = NB, WHERE THEY ARE
C     PB(*,*,NB), PC(*,*,NB), AND PA(*,*,NB) (= DIAGONAL BLOCK).
C (EACH ASTERISK * STANDS FOR AN INDEX THAT RANGES FROM 1 TO MB.)
C
C C. YOU MUST ALSO PROVIDE A SUBROUTINE OF THE FORM..
C     SUBROUTINE ADDA (NEQ, T, Y, MB, NB, PA, PB, PC)
C     DIMENSION Y(NEQ), PA(MB,MB,NB), PB(MB,MB,NB), PC(MB,MB,NB)
C WHICH ADDS THE NONZERO BLOCKS OF THE MATRIX A = A(T,Y) TO THE
C CONTENTS OF THE ARRAYS PA, PB, AND PC, FOLLOWING THE STRUCTURE
C DESCRIPTION IN PARAGRAPH B ABOVE.
C T AND THE Y ARRAY ARE INPUT AND SHOULD NOT BE ALTERED.
C THUS THE AFFECT OF ADDA SHOULD BE THE FOLLOWING..
C     DO 30 K = 1,NB
C       DO 20 J = 1,MB
C         DO 10 I = 1,MB
C           PA(I,J,K) = PA(I,J,K) +
C             ( (I,J) ELEMENT OF K-TH DIAGONAL BLOCK OF A)
C           PB(I,J,K) = PB(I,J,K) +
C             ( (I,J) ELEMENT OF BLOCK IN BLOCK POSITION (K,K+1) OF A,
C             OR IN BLOCK POSITION (NB,NB-2) IF K = NB)
C           PC(I,J,K) = PC(I,J,K) +
C             ( (I,J) ELEMENT OF BLOCK IN BLOCK POSITION (K,K-1) OF A,
C             OR IN BLOCK POSITION (1,3) IF K = 1)
C 10        CONTINUE
C 20      CONTINUE
C 30    CONTINUE
C
C D. FOR THE SAKE OF EFFICIENCY, YOU ARE ENCOURAGED TO SUPPLY THE
C JACOBIAN MATRIX DR/DY IN CLOSED FORM, WHERE R = G(T,Y) - A(T,Y)*S
C (S = A FIXED VECTOR) AS ABOVE.  IF DR/DY IS BEING SUPPLIED,
C USE MF = 21, AND PROVIDE A SUBROUTINE OF THE FORM..
C     SUBROUTINE JAC (NEQ, T, Y, S, MB, NB, PA, PB, PC)
C     DIMENSION Y(NEQ), S(NEQ), PA(MB,MB,NB), PB(MB,MB,NB), PC(MB,MB,NB)
C WHICH COMPUTES DR/DY AS A FUNCTION OF T, Y, AND S.  HERE T, Y, AND
C S ARE INPUTS, AND THE ROUTINE IS TO LOAD DR/DY INTO PA, PB, PC,
C ACCORDING TO THE STRUCTURE DESCRIPTION IN PARAGRAPH B ABOVE.
C THAT IS, LOAD THE DIAGONAL BLOCKS INTO PA, THE SUPERDIAGONAL BLOCKS 
C (AND BLOCK (NB,NB-2) ) INTO PB, AND THE SUBDIAGONAL BLOCKS (AND
C BLOCK (1,3) ) INTO PC.  THE BLOCKS IN BLOCK-ROW K OF DR/DY ARE TO
C BE LOADED INTO PA(*,*,K), PB(*,*,K), AND PC(*,*,K).
C     ONLY NONZERO ELEMENTS NEED BE LOADED, AND THE INDEXING
C OF PA, PB, AND PC IS THE SAME AS IN THE ADDA ROUTINE.
C     NOTE THAT IF A IS INDEPENDENT OF Y (OR THIS DEPENDENCE
C IS WEAK ENOUGH TO BE IGNORED) THEN JAC IS TO COMPUTE DG/DY.
C     IF IT IS NOT FEASIBLE TO PROVIDE A JAC ROUTINE, USE
C MF = 22, AND LSOIBT WILL COMPUTE AN APPROXIMATE JACOBIAN
C INTERNALLY BY DIFFERENCE QUOTIENTS.
C
C E. NEXT DECIDE WHETHER OR NOT TO PROVIDE THE INITIAL VALUE OF THE
C DERIVATIVE VECTOR DY/DT.  IF THE INITIAL VALUE OF A(T,Y) IS
C NONSINGULAR (AND NOT TOO ILL-CONDITIONED), YOU MAY LET LSOIBT COMPUTE
C THIS VECTOR (ISTATE = 0).  (LSOIBT WILL SOLVE THE SYSTEM A*S = G FOR
C S, WITH INITIAL VALUES OF A AND G.)  IF A(T,Y) IS INITIALLY
C SINGULAR, THEN THE SYSTEM IS A DIFFERENTIAL-ALGEBRAIC SYSTEM, AND
C YOU MUST MAKE USE OF THE PARTICULAR FORM OF THE SYSTEM TO COMPUTE THE
C INITIAL VALUES OF Y AND DY/DT.  IN THAT CASE, USE ISTATE = 1 AND
C LOAD THE INITIAL VALUE OF DY/DT INTO THE ARRAY YDOTI.
C THE INPUT ARRAY YDOTI AND THE INITIAL Y ARRAY MUST BE CONSISTENT WITH
C THE EQUATIONS A*DY/DT = G.  THIS IMPLIES THAT THE INITIAL RESIDUAL
C R = G(T,Y) - A(T,Y)*YDOTI   MUST BE APPROXIMATELY ZERO.
C
C F. WRITE A MAIN PROGRAM WHICH CALLS SUBROUTINE LSOIBT ONCE FOR
C EACH POINT AT WHICH ANSWERS ARE DESIRED.  THIS SHOULD ALSO PROVIDE
C FOR POSSIBLE USE OF LOGICAL UNIT 6 FOR OUTPUT OF ERROR MESSAGES
C BY LSOIBT.  ON THE FIRST CALL TO LSOIBT, SUPPLY ARGUMENTS AS FOLLOWS..
C RES    = NAME OF USER SUBROUTINE FOR RESIDUAL FUNCTION R. 
C ADDA   = NAME OF USER SUBROUTINE FOR COMPUTING AND ADDING A(T,Y).
C JAC    = NAME OF USER SUBROUTINE FOR JACOBIAN MATRIX DR/DY
C          (MF = 21).  IF NOT USED, PASS A DUMMY NAME.
C NOTE.. THE NAMES FOR THE RES AND ADDA ROUTINES AND (IF USED) THE
C        JAC ROUTINE MUST BE DECLARED EXTERNAL IN THE CALLING PROGRAM.
C NEQ    = NUMBER OF SCALAR EQUATIONS IN THE SYSTEM.
C Y      = ARRAY OF INITIAL VALUES, OF LENGTH NEQ.
C YDOTI  = ARRAY OF LENGTH NEQ (CONTAINING INITIAL DY/DT IF ISTATE = 1).
C T      = THE INITIAL VALUE OF THE INDEPENDENT VARIABLE.
C TOUT   = FIRST POINT WHERE OUTPUT IS DESIRED (.NE. T).
C ITOL   = 1 OR 2 ACCORDING AS ATOL (BELOW) IS A SCALAR OR ARRAY.
C RTOL   = RELATIVE TOLERANCE PARAMETER (SCALAR). 
C ATOL   = ABSOLUTE TOLERANCE PARAMETER (SCALAR OR ARRAY).
C          THE ESTIMATED LOCAL ERROR IN Y(I) WILL BE CONTROLLED SO AS 
C          TO BE ROUGHLY LESS (IN MAGNITUDE) THAN 
C             EWT(I) = RTOL*ABS(Y(I)) + ATOL     IF ITOL = 1, OR
C             EWT(I) = RTOL*ABS(Y(I)) + ATOL(I)  IF ITOL = 2.
C          THUS THE LOCAL ERROR TEST PASSES IF, IN EACH COMPONENT,
C          EITHER THE ABSOLUTE ERROR IS LESS THAN ATOL (OR ATOL(I)),
C          OR THE RELATIVE ERROR IS LESS THAN RTOL.
C          USE RTOL = 0.0 FOR PURE ABSOLUTE ERROR CONTROL, AND
C          USE ATOL = 0.0 (OR ATOL(I) = 0.0) FOR PURE RELATIVE ERROR
C          CONTROL.  CAUTION.. ACTUAL (GLOBAL) ERRORS MAY EXCEED THESE
C          LOCAL TOLERANCES, SO CHOOSE THEM CONSERVATIVELY. 
C ITASK  = 1 FOR NORMAL COMPUTATION OF OUTPUT VALUES OF Y AT T = TOUT.
C ISTATE = INTEGER FLAG (INPUT AND OUTPUT).  SET ISTATE = 1 IF THE
C          INITIAL DY/DT IS SUPPLIED, AND 0 OTHERWISE.
C IOPT   = 0 TO INDICATE NO OPTIONAL INPUTS USED. 
C RWORK  = REAL WORK ARRAY OF LENGTH AT LEAST..
C             22 + 9*NEQ + 3*MB*MB*NB        FOR MF = 21 OR 22.
C LRW    = DECLARED LENGTH OF RWORK (IN USER-S DIMENSION).
C IWORK  = INTEGER WORK ARRAY OF LENGTH AT LEAST 20 + NEQ.
C          INPUT IN IWORK(1) THE BLOCK SIZE MB AND IN IWORK(2) THE
C          NUMBER NB OF BLOCKS IN EACH DIRECTION ALONG THE MATRIX A.
C          THESE MUST SATISFY  MB .GE. 1, NB .GE. 4, AND MB*NB = NEQ. 
C LIW    = DECLARED LENGTH OF IWORK (IN USER-S DIMENSION).
C MF     = METHOD FLAG.  STANDARD VALUES ARE..
C          21 FOR A USER-SUPPLIED JACOBIAN.
C          22 FOR AN INTERNALLY GENERATED JACOBIAN.
C          FOR OTHER CHOICES OF MF, SEE THE PARAGRAPH ON MF IN
C          THE FULL DESCRIPTION BELOW.
C NOTE THAT THE MAIN PROGRAM MUST DECLARE ARRAYS Y, YDOTI, RWORK, IWORK,
C AND POSSIBLY ATOL.
C
C G. THE OUTPUT FROM THE FIRST CALL (OR ANY CALL) IS..
C      Y = ARRAY OF COMPUTED VALUES OF Y(T) VECTOR.
C      T = CORRESPONDING VALUE OF INDEPENDENT VARIABLE (NORMALLY TOUT).
C ISTATE = 2  IF LSOIBT WAS SUCCESSFUL, NEGATIVE OTHERWISE. 
C          -1 MEANS EXCESS WORK DONE ON THIS CALL (CHECK ALL INPUTS). 
C          -2 MEANS EXCESS ACCURACY REQUESTED (TOLERANCES TOO SMALL). 
C          -3 MEANS ILLEGAL INPUT DETECTED (SEE PRINTED MESSAGE).
C          -4 MEANS REPEATED ERROR TEST FAILURES (CHECK ALL INPUTS).
C          -5 MEANS REPEATED CONVERGENCE FAILURES (PERHAPS BAD JACOBIAN
C             SUPPLIED OR WRONG CHOICE OF TOLERANCES).
C          -6 MEANS ERROR WEIGHT BECAME ZERO DURING PROBLEM. (SOLUTION
C             COMPONENT I VANISHED, AND ATOL OR ATOL(I) = 0.)
C          -7 CANNOT OCCUR IN CASUAL USE.
C          -8 MEANS LSOIBT WAS UNABLE TO COMPUTE THE INITIAL DY/DT.
C             IN CASUAL USE, THIS MEANS A(T,Y) IS INITIALLY SINGULAR. 
C             SUPPLY YDOTI AND USE ISTATE = 1 ON THE FIRST CALL.
C
C  IF LSOIBT RETURNS ISTATE = -1, -4, OR -5, THEN THE OUTPUT OF
C  LSOIBT ALSO INCLUDES YDOTI = ARRAY CONTAINING RESIDUAL VECTOR
C  R = G - A * DY/DT  EVALUATED AT THE CURRENT T, Y, AND DY/DT.
C
C H. TO CONTINUE THE INTEGRATION AFTER A SUCCESSFUL RETURN, SIMPLY
C RESET TOUT AND CALL LSOIBT AGAIN.  NO OTHER PARAMETERS NEED BE RESET.
C
C
C-----------------------------------------------------------------------
C EXAMPLE PROBLEM.
C
C THE FOLLOWING IS AN EXAMPLE PROBLEM, WITH THE CODING NEEDED
C FOR ITS SOLUTION BY LSOIBT.  THE PROBLEM COMES FROM THE PARTIAL
C DIFFERENTIAL EQUATION (THE BURGERS EQUATION)
C   DU/DT  =  - U * DU/DX  +  ETA * D**2 U/DX**2,   ETA = .05,
C ON -1 .LE. X .LE. 1.  THE BOUNDARY CONDITIONS ARE
C   DU/DX = 0  AT X = -1 AND AT X = 1.
C THE INITIAL PROFILE IS A SQUARE WAVE, 
C   U = 1 IN ABS(X) .LT. .5,  U = .5 AT ABS(X) = .5,  U = 0 ELSEWHERE.
C THE P.D.E. IS DISCRETIZED IN X BY A SIMPLIFIED GALERKIN METHOD,
C USING PIECEWISE LINEAR BASIS FUNCTIONS, ON A GRID OF 40 INTERVALS.
C THE EQUATIONS AT X = -1 AND 1 USE A 3-POINT DIFFERENCE APPROXIMATION
C FOR THE RIGHT-HAND SIDE.  THE RESULT IS A SYSTEM A * DY/DT = G(Y),
C OF SIZE NEQ = 41, WHERE Y(I) IS THE APPROXIMATION TO U AT X = X(I), 
C WITH X(I) = -1 + (I-1)*DELX, DELX = 2/(NEQ-1) = .05.  THE INDIVIDUAL
C EQUATIONS IN THE SYSTEM ARE 
C   DY(1)/DT = ( Y(3) - 2*Y(2) + Y(1) ) * ETA / DELX**2,
C   DY(NEQ)/DT = ( Y(NEQ-2) - 2*Y(NEQ-1) + Y(NEQ) ) * ETA / DELX**2,
C AND FOR I = 2, 3, ..., NEQ-1,
C   (1/6) DY(I-1)/DT + (4/6) DY(I)/DT + (1/6) DY(I+1)/DT
C       = ( Y(I-1)**2 - Y(I+1)**2 ) / (4*DELX)
C         + ( Y(I+1) - 2*Y(I) + Y(I-1) ) * ETA / DELX**2.
C THE FOLLOWING CODING SOLVES THE PROBLEM WITH MF = 21, WITH OUTPUT
C OF SOLUTION STATISTICS AT T = .1, .2, .3, AND .4, AND OF THE
C SOLUTION VECTOR AT T = .4.  HERE THE BLOCK SIZE IS JUST MB = 1.
C
C     EXTERNAL RESID, ADDABT, JACBT
C     DOUBLE PRECISION ATOL, RTOL, RWORK, T, TOUT, Y, YDOTI 
C     DIMENSION Y(41), YDOTI(41), RWORK(514), IWORK(61)
C     NEQ = 41
C     DO 10 I = 1,NEQ
C  10   Y(I) = 0.0D0
C     Y(11) = 0.5D0 
C     DO 20 I = 12,30
C  20   Y(I) = 1.0D0
C     Y(31) = 0.5D0 
C     T = 0.0D0
C     TOUT = 0.1D0
C     ITOL = 1
C     RTOL = 1.0D-4 
C     ATOL = 1.0D-5 
C     ITASK = 1
C     ISTATE = 0
C     IOPT = 0
C     LRW = 514
C     LIW = 61
C     IWORK(1) = 1
C     IWORK(2) = NEQ
C     MF = 21
C     DO 40 IO = 1,4
C       CALL LSOIBT (RESID, ADDABT, JACBT, NEQ, Y, YDOTI, T, TOUT,
C    1   ITOL,RTOL,ATOL, ITASK, ISTATE, IOPT, RWORK,LRW,IWORK,LIW, MF)
C       WRITE (6,30) T, IWORK(11), IWORK(12), IWORK(13)
C  30   FORMAT(7H AT T =,F5.2,14H   NO. STEPS =,I4,11H  NO. R-S =,I4, 
C    1   11H  NO. J-S =,I3)
C       IF (ISTATE .NE. 2)  GO TO 90
C       TOUT = TOUT + 0.1D0
C  40   CONTINUE
C     WRITE(6,50) (Y(I),I=1,NEQ)
C  50 FORMAT(/24H FINAL SOLUTION VALUES../9(5E12.4/))
C     STOP
C  90 WRITE(6,95) ISTATE
C  95 FORMAT(///22H ERROR HALT.. ISTATE =,I3)
C     STOP
C     END 
C
C     SUBROUTINE RESID (N, T, Y, S, R, IRES)
C     DOUBLE PRECISION DELX, ETA, EODSQ, R, S, T, Y
C     DIMENSION Y(N), S(N), R(N)
C     DATA ETA/0.05D0/, DELX/0.05D0/
C     EODSQ = ETA/DELX**2
C     R(1) = EODSQ*(Y(3) - 2.0D0*Y(2) + Y(1)) - S(1)
C     NM1 = N - 1
C     DO 10 I = 2,NM1
C       R(I) = (Y(I-1)**2 - Y(I+1)**2)/(4.0D0*DELX)
C    1        + EODSQ*(Y(I+1) - 2.0D0*Y(I) + Y(I-1))
C    2        - (S(I-1) + 4.0D0*S(I) + S(I+1))/6.0D0
C  10   CONTINUE
C     R(N) = EODSQ*(Y(N-2) - 2.0D0*Y(NM1) + Y(N)) - S(N)
C     RETURN
C     END 
C
C     SUBROUTINE ADDABT (N, T, Y, MB, NB, PA, PB, PC)
C     DOUBLE PRECISION PA, PB, PC, T, Y 
C     DIMENSION Y(N), PA(MB,MB,NB), PB(MB,MB,NB), PC(MB,MB,NB)
C     PA(1,1,1) = PA(1,1,1) + 1.0D0
C     NM1 = N - 1
C     DO 10 K = 2,NM1
C       PA(1,1,K) = PA(1,1,K) + (4.0D0/6.0D0)
C       PB(1,1,K) = PB(1,1,K) + (1.0D0/6.0D0)
C       PC(1,1,K) = PC(1,1,K) + (1.0D0/6.0D0)
C  10   CONTINUE
C     PA(1,1,N) = PA(1,1,N) + 1.0D0
C     RETURN
C     END 
C
C     SUBROUTINE JACBT (N, T, Y, S, MB, NB, PA, PB, PC)
C     DOUBLE PRECISION DELX, ETA, EODSQ, PA, PB, PC, S, T, Y
C     DIMENSION Y(N), S(N), PA(MB,MB,NB),PB(MB,MB,NB),PC(MB,MB,NB)
C     DATA ETA/0.05D0/, DELX/0.05D0/
C     EODSQ = ETA/DELX**2
C     PA(1,1,1) = EODSQ
C     PB(1,1,1) = -2.0D0*EODSQ
C     PC(1,1,1) = EODSQ
C     DO 10 K = 2,N 
C       PA(1,1,K) = -2.0D0*EODSQ
C       PB(1,1,K) = -Y(K+1)*(0.5D0/DELX) + EODSQ
C       PC(1,1,K) = Y(K-1)*(0.5D0/DELX) + EODSQ
C  10   CONTINUE
C     PB(1,1,N) = EODSQ
C     PC(1,1,N) = -2.0D0*EODSQ
C     PA(1,1,N) = EODSQ
C     RETURN
C     END 
C
C THE OUTPUT OF THIS PROGRAM (ON A CDC-7600 IN SINGLE PRECISION)
C IS AS FOLLOWS..
C
C AT T = 0.10   NO. STEPS =  35  NO. R-S =  45  NO. J-S =  9
C AT T = 0.20   NO. STEPS =  43  NO. R-S =  54  NO. J-S = 10
C AT T = 0.30   NO. STEPS =  48  NO. R-S =  60  NO. J-S = 11
C AT T = 0.40   NO. STEPS =  51  NO. R-S =  64  NO. J-S = 12
C
C FINAL SOLUTION VALUES..
C  1.2747E-02  1.1997E-02  1.5560E-02  2.3767E-02  3.7224E-02
C  5.6646E-02  8.2645E-02  1.1557E-01  1.5541E-01  2.0177E-01
C  2.5397E-01  3.1104E-01  3.7189E-01  4.3530E-01  5.0000E-01
C  5.6472E-01  6.2816E-01  6.8903E-01  7.4612E-01  7.9829E-01
C  8.4460E-01  8.8438E-01  9.1727E-01  9.4330E-01  9.6281E-01
C  9.7632E-01  9.8426E-01  9.8648E-01  9.8162E-01  9.6617E-01
C  9.3374E-01  8.7535E-01  7.8236E-01  6.5321E-01  5.0003E-01
C  3.4709E-01  2.1876E-01  1.2771E-01  7.3671E-02  5.0642E-02
C  5.4496E-02
C-----------------------------------------------------------------------
C FULL DESCRIPTION OF USER INTERFACE TO LSOIBT.
C
C THE USER INTERFACE TO LSOIBT CONSISTS OF THE FOLLOWING PARTS.
C
C I.   THE CALL SEQUENCE TO SUBROUTINE LSOIBT, WHICH IS A DRIVER
C      ROUTINE FOR THE SOLVER.  THIS INCLUDES DESCRIPTIONS OF BOTH
C      THE CALL SEQUENCE ARGUMENTS AND OF USER-SUPPLIED ROUTINES.
C      FOLLOWING THESE DESCRIPTIONS IS A DESCRIPTION OF
C      OPTIONAL INPUTS AVAILABLE THROUGH THE CALL SEQUENCE, AND THEN
C      A DESCRIPTION OF OPTIONAL OUTPUTS (IN THE WORK ARRAYS).
C
C II.  DESCRIPTIONS OF OTHER ROUTINES IN THE LSOIBT PACKAGE THAT MAY BE
C      (OPTIONALLY) CALLED BY THE USER.  THESE PROVIDE THE ABILITY TO 
C      ALTER ERROR MESSAGE HANDLING, SAVE AND RESTORE THE INTERNAL
C      COMMON, AND OBTAIN SPECIFIED DERIVATIVES OF THE SOLUTION Y(T). 
C
C III. DESCRIPTIONS OF COMMON BLOCKS TO BE DECLARED IN OVERLAY
C      OR SIMILAR ENVIRONMENTS, OR TO BE SAVED WHEN DOING AN INTERRUPT
C      OF THE PROBLEM AND CONTINUED SOLUTION LATER.
C
C IV.  DESCRIPTION OF TWO ROUTINES IN THE LSOIBT PACKAGE, EITHER OF
C      WHICH THE USER MAY REPLACE WITH HIS OWN VERSION, IF DESIRED.
C      THESE RELATE TO THE MEASUREMENT OF ERRORS. 
C
C-----------------------------------------------------------------------
C PART I.  CALL SEQUENCE.
C
C THE CALL SEQUENCE PARAMETERS USED FOR INPUT ONLY ARE
C     RES, ADDA, JAC, NEQ, TOUT, ITOL, RTOL, ATOL, ITASK,
C     IOPT, LRW, LIW, MF,
C AND THOSE USED FOR BOTH INPUT AND OUTPUT ARE
C     Y, T, ISTATE, YDOTI.
C THE WORK ARRAYS RWORK AND IWORK ARE ALSO USED FOR ADDITIONAL AND
C OPTIONAL INPUTS AND OPTIONAL OUTPUTS.  (THE TERM OUTPUT HERE REFERS 
C TO THE RETURN FROM SUBROUTINE LSOIBT TO THE USER-S CALLING PROGRAM.)
C
C THE LEGALITY OF INPUT PARAMETERS WILL BE THOROUGHLY CHECKED ON THE
C INITIAL CALL FOR THE PROBLEM, BUT NOT CHECKED THEREAFTER UNLESS A
C CHANGE IN INPUT PARAMETERS IS FLAGGED BY ISTATE = 3 ON INPUT.
C
C THE DESCRIPTIONS OF THE CALL ARGUMENTS ARE AS FOLLOWS.
C
C RES    = THE NAME OF THE USER-SUPPLIED SUBROUTINE WHICH SUPPLIES
C          THE RESIDUAL VECTOR FOR THE ODE SYSTEM, DEFINED BY
C            R = G(T,Y) - A(T,Y) * S
C          AS A FUNCTION OF THE SCALAR T AND THE VECTORS
C          S AND Y ( S APPROXIMATES DY/DT ). THIS 
C          SUBROUTINE IS TO HAVE THE FORM
C              SUBROUTINE RES ( NEQ, T, Y, S, R, IRES )
C              DIMENSION Y(1), S(1), R(1)
C          WHERE NEQ, T, Y, S, AND IRES ARE INPUT, AND R AND
C          IRES ARE OUTPUT. Y, S, AND R ARE ARRAYS OF LENGTH NEQ.
C          IN DIMENSION STATEMENTS SUCH AS THAT ABOVE, 1 IS A
C          DUMMY DIMENSION. IT CAN BE REPLACED BY ANY VALUE.
C             ON INPUT, IRES INDICATES HOW LSOIBT WILL USE THE
C          RETURNED ARRAY R, AS FOLLOWS..
C             IRES = 1  MEANS THAT LSOIBT NEEDS THE FULL RESIDUAL,
C                       R = G - A*S, EXACTLY.
C             IRES = -1 MEANS THAT LSOIBT IS USING R ONLY TO COMPUTE
C                       THE JACOBIAN DR/DY BY DIFFERENCE QUOTIENTS.
C          THE RES ROUTINE CAN IGNORE IRES, OR IT CAN OMIT SOME TERMS 
C          IF IRES = -1.  IF A DOES NOT DEPEND ON Y, THEN RES CAN
C          JUST RETURN R = G WHEN IRES = -1.  IF G - A*S CONTAINS OTHER
C          ADDITIVE TERMS THAT ARE INDEPENDENT OF Y, THESE CAN ALSO BE
C          DROPPED, IF DONE CONSISTENTLY, WHEN IRES = -1.
C             THE SUBROUTINE SHOULD SET THE FLAG IRES IF IT 
C          ENCOUNTERS A HALT CONDITION OR ILLEGAL INPUT.
C          OTHERWISE, IT SHOULD NOT RESET IRES.  ON OUTPUT, 
C             IRES = 1 OR -1 REPRESENTS A NORMAL RETURN, AND
C          LSOIBT CONTINUES INTEGRATING THE ODE.  LEAVE IRES
C          UNCHANGED FROM ITS INPUT VALUE.
C             IRES = 2 TELLS LSOIBT TO IMMEDIATELY RETURN CONTROL
C          TO THE CALLING PROGRAM, WITH ISTATE = 3.  THIS LETS
C          THE CALLING PROGRAM CHANGE PARAMETERS OF THE PROB-
C          LEM IF NECESSARY.
C             IRES = 3 REPRESENTS AN ERROR CONDITION (FOR EXAMPLE, AN 
C          ILLEGAL VALUE OF Y). LSOIBT TRIES TO INTEGRATE THE ODE
C          WITHOUT GETTING IRES = 3 FROM RES.  IF IT CANNOT, LSOIBT
C          RETURNS WITH ISTATE = -7 OR -1.
C             ON AN LSOIBT RETURN WITH ISTATE = 3, -1, OR -7, THE VALUES
C          OF T AND Y RETURNED CORRESPOND TO THE LAST POINT REACHED
C          SUCCESSFULLY WITHOUT GETTING THE FLAG IRES = 2 OR 3.
C             THE FLAG VALUES IRES = 2 AND 3 SHOULD NOT BE USED TO
C          HANDLE SWITCHES OR ROOT-STOP CONDITIONS.  THIS IS BETTER
C          DONE BY CALLING LSOIBT IN A ONE-STEP MODE AND CHECKING THE 
C          STOPPING FUNCTION FOR A SIGN CHANGE AT EACH STEP.
C             IF QUANTITIES COMPUTED IN THE RES ROUTINE ARE NEEDED
C          EXTERNALLY TO LSOIBT, AN EXTRA CALL TO RES SHOULD BE MADE
C          FOR THIS PURPOSE, FOR CONSISTENT AND ACCURATE RESULTS.
C          TO GET THE CURRENT DY/DT FOR THE S ARGUMENT, USE INTDY.
C             RES MUST BE DECLARED EXTERNAL IN THE CALLING
C          PROGRAM.  SEE NOTE BELOW FOR MORE ABOUT RES.
C
C ADDA   = THE NAME OF THE USER-SUPPLIED SUBROUTINE WHICH ADDS THE
C          MATRIX A = A(T,Y) TO ANOTHER MATRIX, P, STORED IN
C          BLOCK-TRIDIAGONAL FORM.  THIS ROUTINE IS TO HAVE THE FORM
C               SUBROUTINE ADDA (NEQ, T, Y, MB, NB, PA, PB, PC)
C               DIMENSION Y(NEQ),
C              1    PA(MB,MB,NB), PB(MB,MB,NB), PC(MB,MB,NB)
C          WHERE NEQ, T, Y, MB, NB, AND THE ARRAYS PA, PB, AND PC
C          ARE INPUT, AND THE ARRAYS PA, PB, AND PC ARE OUTPUT.
C          Y IS AN ARRAY OF LENGTH NEQ, AND THE ARRAYS PA, PB, PC
C          ARE ALL MB BY MB BY NB.
C             HERE A BLOCK-TRIDIAGONAL STRUCTURE IS ASSUMED FOR A(T,Y),
C          AND ALSO FOR THE MATRIX P TO WHICH A IS ADDED HERE,
C          AS DESCRIBED IN PARAGRAPH B OF THE SUMMARY OF USAGE ABOVE. 
C          THUS THE AFFECT OF ADDA SHOULD BE THE FOLLOWING..
C               DO 30 K = 1,NB
C                 DO 20 J = 1,MB
C                   DO 10 I = 1,MB
C                     PA(I,J,K) = PA(I,J,K) +
C                       ( (I,J) ELEMENT OF K-TH DIAGONAL BLOCK OF A)
C                     PB(I,J,K) = PB(I,J,K) +
C                       ( (I,J) ELEMENT OF BLOCK (K,K+1) OF A,
C                       OR BLOCK (NB,NB-2) IF K = NB)
C                     PC(I,J,K) = PC(I,J,K) +
C                       ( (I,J) ELEMENT OF BLOCK (K,K-1) OF A,
C                       OR BLOCK (1,3) IF K = 1)
C           10        CONTINUE
C           20      CONTINUE
C           30    CONTINUE
C             ADDA MUST BE DECLARED EXTERNAL IN THE CALLING PROGRAM.
C          SEE NOTE BELOW FOR MORE INFORMATION ABOUT ADDA.
C
C JAC    = THE NAME OF THE USER-SUPPLIED SUBROUTINE WHICH SUPPLIES
C          THE JACOBIAN MATRIX, DR/DY, WHERE R = G-A*S.  JAC IS
C          REQUIRED IF MITER = 1 -- OTHERWISE A DUMMY NAME CAN BE
C          PASSED. THIS SUBROUTINE IS TO HAVE THE FORM
C               SUBROUTINE JAC (NEQ, T, Y, S, MB, NB, PA, PB, PC)
C               DIMENSION Y(NEQ), S(NEQ),
C              1    PA(MB,MB,NB), PB(MB,MB,NB), PC(MB,MB,NB)
C          WHERE NEQ, T, Y, S, MB, NB, AND THE ARRAYS PA, PB, AND PC
C          ARE INPUT, AND THE ARRAYS PA, PB, AND PC ARE OUTPUT.
C          Y AND S ARE ARRAYS OF LENGTH NEQ, AND THE ARRAYS PA, PB, PC
C          ARE ALL MB BY MB BY NB.
C          PA, PB, AND PC ARE TO BE LOADED WITH PARTIAL DERIVATIVES
C          (ELEMENTS OF THE JACOBIAN MATRIX) ON OUTPUT, IN TERMS OF THE
C          BLOCK-TRIDIAGONAL STRUCTURE ASSUMED, AS DESCRIBED
C          IN PARAGRAPH B OF THE SUMMARY OF USAGE ABOVE.
C          THAT IS, LOAD THE DIAGONAL BLOCKS INTO PA, THE
C          SUPERDIAGONAL BLOCKS (AND BLOCK (NB,NB-2) ) INTP PB, AND
C          THE SUBDIAGONAL BLOCKS (AND BLOCK (1,3) ) INTO PC.
C          THE BLOCKS IN BLOCK-ROW K OF DR/DY ARE TO BE LOADED INTO
C          PA(*,*,K), PB(*,*,K), AND PC(*,*,K).
C          THUS THE AFFECT OF JAC SHOULD BE THE FOLLOWING.. 
C               DO 30 K = 1,NB
C                 DO 20 J = 1,MB
C                   DO 10 I = 1,MB
C                     PA(I,J,K) = ( (I,J) ELEMENT OF
C                       K-TH DIAGONAL BLOCK OF DR/DY)
C                     PB(I,J,K) = ( (I,J) ELEMENT OF BLOCK (K,K+1)
C                       OF DR/DY, OR BLOCK (NB,NB-2) IF K = NB)
C                     PC(I,J,K) = ( (I,J) ELEMENT OF BLOCK (K,K-1)
C                       OF DR/DY, OR BLOCK (1,3) IF K = 1)
C           10        CONTINUE
C           20      CONTINUE
C           30    CONTINUE
C               PA, PB, AND PC ARE PRESET TO ZERO BY THE SOLVER,
C          SO THAT ONLY THE NONZERO ELEMENTS NEED BE LOADED BY JAC.
C          EACH CALL TO JAC IS PRECEDED BY A CALL TO RES WITH THE SAME
C          ARGUMENTS NEQ, T, Y, AND S.  THUS TO GAIN SOME EFFICIENCY, 
C          INTERMEDIATE QUANTITIES SHARED BY BOTH CALCULATIONS MAY BE 
C          SAVED IN A USER COMMON BLOCK BY RES AND NOT RECOMPUTED BY JAC
C          IF DESIRED.  ALSO, JAC MAY ALTER THE Y ARRAY, IF DESIRED.
C               JAC NEED NOT PROVIDE DR/DY EXACTLY.  A CRUDE
C          APPROXIMATION WILL DO, SO THAT LSOIBT MAY BE USED WHEN
C          A AND DR/DY ARE NOT REALLY BLOCK-TRIDIAGONAL, BUT ARE CLOSE
C          TO MATRICES THAT ARE.
C               JAC MUST BE DECLARED EXTERNAL IN THE CALLING PROGRAM. 
C               SEE NOTE BELOW FOR MORE ABOUT JAC.
C
C       NOTE ON RES, ADDA, AND JAC--  THESE
C          SUBROUTINES MAY ACCESS USER-DEFINED QUANTITIES IN
C          NEQ(2),... AND/OR IN Y(NEQ(1)+1),... IF NEQ IS AN ARRAY
C          (DIMENSIONED IN THE SUBROUTINES) AND/OR Y HAS LENGTH
C          EXCEEDING NEQ(1).  HOWEVER, THESE ROUTINES SHOULD NOT ALTER
C          NEQ(1), Y(1),...,Y(NEQ) OR ANY OTHER INPUT VARIABLES.
C          SEE THE DESCRIPTIONS OF NEQ AND Y BELOW.
C
C NEQ    = THE SIZE OF THE SYSTEM (NUMBER OF FIRST ORDER ORDINARY
C          DIFFERENTIAL EQUATIONS OR SCALAR ALGEBRAIC EQUATIONS).
C          USED ONLY FOR INPUT.
C          NEQ MAY BE DECREASED, BUT NOT INCREASED, DURING THE PROBLEM.
C          IF NEQ IS DECREASED (WITH ISTATE = 3 ON INPUT), THE
C          REMAINING COMPONENTS OF Y SHOULD BE LEFT UNDISTURBED, IF
C          THESE ARE TO BE ACCESSED IN RES, ADDA, OR JAC.
C
C          NORMALLY, NEQ IS A SCALAR, AND IT IS GENERALLY REFERRED TO 
C          AS A SCALAR IN THIS USER INTERFACE DESCRIPTION.  HOWEVER,
C          NEQ MAY BE AN ARRAY, WITH NEQ(1) SET TO THE SYSTEM SIZE.
C          (THE LSOIBT PACKAGE ACCESSES ONLY NEQ(1).)  IN EITHER CASE,
C          THIS PARAMETER IS PASSED AS THE NEQ ARGUMENT IN ALL CALLS
C          TO RES, ADDA, AND JAC.  HENCE, IF IT IS AN ARRAY,
C          LOCATIONS NEQ(2),... MAY BE USED TO STORE OTHER INTEGER DATA
C          AND PASS IT TO  RES, ADDA, OR JAC.  EACH SUCH SUBROUTINE
C          MUST INCLUDE NEQ IN A DIMENSION STATEMENT IN THAT CASE.
C
C Y      = A REAL ARRAY FOR THE VECTOR OF DEPENDENT VARIABLES, OF
C          LENGTH NEQ OR MORE.  USED FOR BOTH INPUT AND OUTPUT ON THE 
C          FIRST CALL (ISTATE = 0 OR 1), AND ONLY FOR OUTPUT ON OTHER 
C          CALLS.  ON THE FIRST CALL, Y MUST CONTAIN THE VECTOR OF
C          INITIAL VALUES.  ON OUTPUT, Y CONTAINS THE COMPUTED SOLUTION
C          VECTOR, EVALUATED AT T.  IF DESIRED, THE Y ARRAY MAY BE USED
C          FOR OTHER PURPOSES BETWEEN CALLS TO THE SOLVER.
C
C          THIS ARRAY IS PASSED AS THE Y ARGUMENT IN ALL CALLS TO RES,
C          ADDA, AND JAC.  HENCE ITS LENGTH MAY EXCEED NEQ, 
C          AND LOCATIONS Y(NEQ+1),... MAY BE USED TO STORE OTHER REAL 
C          DATA AND PASS IT TO RES, ADDA, OR JAC.  (THE LSOIBT
C          PACKAGE ACCESSES ONLY Y(1),...,Y(NEQ). )
C
C YDOTI  = A REAL ARRAY FOR THE INITIAL VALUE OF THE VECTOR 
C          DY/DT AND FOR WORK SPACE, OF DIMENSION AT LEAST NEQ.
C
C          ON INPUT...
C            IF ISTATE = 0 THEN LSOIBT WILL COMPUTE THE INITIAL VALUE 
C          OF DY/DT, IF A IS NONSINGULAR.  THUS YDOTI WILL
C          SERVE ONLY AS WORK SPACE AND MAY HAVE ANY VALUE. 
C            IF ISTATE = 1 THEN YDOTI MUST CONTAIN THE INITIAL VALUE
C          OF DY/DT.
C            IF ISTATE = 2 OR 3 (CONTINUATION CALLS) THEN YDOTI
C          MAY HAVE ANY VALUE.
C            N.B.- IF THE INITIAL VALUE OF A IS SINGULAR, THEN
C          LSOIBT CANNOT COMPUTE THE INITIAL VALUE OF DY/DT, SO
C          IT MUST BE PROVIDED IN YDOTI, WITH ISTATE=1.
C
C          ON OUTPUT, WHEN LSOIBT TERMINATES ABNORMALLY WITH ISTATE = 
C          -1, -4, OR -5, YDOTI WILL CONTAIN THE RESIDUAL
C          R = G(T,Y) - A(T,Y)*(DY/DT).  IF R IS LARGE, T IS NEAR
C          ITS INITIAL VALUE, AND YDOTI IS SUPPLIED WITH ISTATE=1,
C          THERE MAY HAVE BEEN AN INCORRECT INPUT VALUE OF
C          YDOTI = DY/DT OR THE PROBLEM ( AS GIVEN TO LSOIBT )
C          MAY NOT HAVE A SOLUTION.
C
C          IF DESIRED, THE YDOTI ARRAY MAY BE USED FOR OTHER
C          PURPOSES BETWEEN CALLS TO THE SOLVER.
C
C T      = THE INDEPENDENT VARIABLE.  ON INPUT, T IS USED ONLY ON THE 
C          FIRST CALL, AS THE INITIAL POINT OF THE INTEGRATION.
C          ON OUTPUT, AFTER EACH CALL, T IS THE VALUE AT WHICH A
C          COMPUTED SOLUTION Y IS EVALUATED (USUALLY THE SAME AS TOUT).
C          ON AN ERROR RETURN, T IS THE FARTHEST POINT REACHED.
C
C TOUT   = THE NEXT VALUE OF T AT WHICH A COMPUTED SOLUTION IS DESIRED.
C          USED ONLY FOR INPUT.
C
C          WHEN STARTING THE PROBLEM (ISTATE = 0 OR 1), TOUT MAY BE
C          EQUAL TO T FOR ONE CALL, THEN SHOULD .NE. T FOR THE NEXT
C          CALL.  FOR THE INITIAL T, AN INPUT VALUE OF TOUT .NE. T IS 
C          USED IN ORDER TO DETERMINE THE DIRECTION OF THE INTEGRATION
C          (I.E. THE ALGEBRAIC SIGN OF THE STEP SIZES) AND THE ROUGH
C          SCALE OF THE PROBLEM.  INTEGRATION IN EITHER DIRECTION
C          (FORWARD OR BACKWARD IN T) IS PERMITTED.
C
C          IF ITASK = 2 OR 5 (ONE-STEP MODES), TOUT IS IGNORED AFTER
C          THE FIRST CALL (I.E. THE FIRST CALL WITH TOUT .NE. T).
C          OTHERWISE, TOUT IS REQUIRED ON EVERY CALL.
C
C          IF ITASK = 1, 3, OR 4, THE VALUES OF TOUT NEED NOT BE
C          MONOTONE, BUT A VALUE OF TOUT WHICH BACKS UP IS LIMITED
C          TO THE CURRENT INTERNAL T INTERVAL, WHOSE ENDPOINTS ARE
C          TCUR - HU AND TCUR (SEE OPTIONAL OUTPUTS, BELOW, FOR
C          TCUR AND HU).
C
C ITOL   = AN INDICATOR FOR THE TYPE OF ERROR CONTROL.  SEE 
C          DESCRIPTION BELOW UNDER ATOL.  USED ONLY FOR INPUT.
C
C RTOL   = A RELATIVE ERROR TOLERANCE PARAMETER, EITHER A SCALAR OR
C          AN ARRAY OF LENGTH NEQ.  SEE DESCRIPTION BELOW UNDER ATOL. 
C          INPUT ONLY.
C
C ATOL   = AN ABSOLUTE ERROR TOLERANCE PARAMETER, EITHER A SCALAR OR
C          AN ARRAY OF LENGTH NEQ.  INPUT ONLY.
C
C             THE INPUT PARAMETERS ITOL, RTOL, AND ATOL DETERMINE
C          THE ERROR CONTROL PERFORMED BY THE SOLVER.  THE SOLVER WILL
C          CONTROL THE VECTOR E = (E(I)) OF ESTIMATED LOCAL ERRORS
C          IN Y, ACCORDING TO AN INEQUALITY OF THE FORM
C                      RMS-NORM OF ( E(I)/EWT(I) )   .LE.   1,
C          WHERE       EWT(I) = RTOL(I)*ABS(Y(I)) + ATOL(I),
C          AND THE RMS-NORM (ROOT-MEAN-SQUARE NORM) HERE IS 
C          RMS-NORM(V) = SQRT(SUM V(I)**2 / NEQ).  HERE EWT = (EWT(I))
C          IS A VECTOR OF WEIGHTS WHICH MUST ALWAYS BE POSITIVE, AND
C          THE VALUES OF RTOL AND ATOL SHOULD ALL BE NON-NEGATIVE.
C          THE FOLLOWING TABLE GIVES THE TYPES (SCALAR/ARRAY) OF
C          RTOL AND ATOL, AND THE CORRESPONDING FORM OF EWT(I).
C
C             ITOL    RTOL       ATOL          EWT(I)
C              1     SCALAR     SCALAR     RTOL*ABS(Y(I)) + ATOL
C              2     SCALAR     ARRAY      RTOL*ABS(Y(I)) + ATOL(I)
C              3     ARRAY      SCALAR     RTOL(I)*ABS(Y(I)) + ATOL
C              4     ARRAY      SCALAR     RTOL(I)*ABS(Y(I)) + ATOL(I)
C
C          WHEN EITHER OF THESE PARAMETERS IS A SCALAR, IT NEED NOT
C          BE DIMENSIONED IN THE USER-S CALLING PROGRAM.
C
C          IF NONE OF THE ABOVE CHOICES (WITH ITOL, RTOL, AND ATOL
C          FIXED THROUGHOUT THE PROBLEM) IS SUITABLE, MORE GENERAL
C          ERROR CONTROLS CAN BE OBTAINED BY SUBSTITUTING
C          USER-SUPPLIED ROUTINES FOR THE SETTING OF EWT AND/OR FOR
C          THE NORM CALCULATION.  SEE PART IV BELOW.
C
C          IF GLOBAL ERRORS ARE TO BE ESTIMATED BY MAKING A REPEATED
C          RUN ON THE SAME PROBLEM WITH SMALLER TOLERANCES, THEN ALL
C          COMPONENTS OF RTOL AND ATOL (I.E. OF EWT) SHOULD BE SCALED 
C          DOWN UNIFORMLY
C
C ITASK  = AN INDEX SPECIFYING THE TASK TO BE PERFORMED.
C          INPUT ONLY.  ITASK HAS THE FOLLOWING VALUES AND MEANINGS.
C          1  MEANS NORMAL COMPUTATION OF OUTPUT VALUES OF Y(T) AT
C             T = TOUT (BY OVERSHOOTING AND INTERPOLATING). 
C          2  MEANS TAKE ONE STEP ONLY AND RETURN.
C          3  MEANS STOP AT THE FIRST INTERNAL MESH POINT AT OR
C             BEYOND T = TOUT AND RETURN.
C          4  MEANS NORMAL COMPUTATION OF OUTPUT VALUES OF Y(T) AT
C             T = TOUT BUT WITHOUT OVERSHOOTING T = TCRIT.
C             TCRIT MUST BE INPUT AS RWORK(1).  TCRIT MAY BE EQUAL TO 
C             OR BEYOND TOUT, BUT NOT BEHIND IT IN THE DIRECTION OF
C             INTEGRATION.  THIS OPTION IS USEFUL IF THE PROBLEM
C             HAS A SINGULARITY AT OR BEYOND T = TCRIT.
C          5  MEANS TAKE ONE STEP, WITHOUT PASSING TCRIT, AND RETURN. 
C             TCRIT MUST BE INPUT AS RWORK(1).
C
C          NOTE..  IF ITASK = 4 OR 5 AND THE SOLVER REACHES TCRIT
C          (WITHIN ROUNDOFF), IT WILL RETURN T = TCRIT (EXACTLY) TO
C          INDICATE THIS (UNLESS ITASK = 4 AND TOUT COMES BEFORE TCRIT,
C          IN WHICH CASE ANSWERS AT T = TOUT ARE RETURNED FIRST).
C
C ISTATE = AN INDEX USED FOR INPUT AND OUTPUT TO SPECIFY THE
C          STATE OF THE CALCULATION.
C
C          ON INPUT, THE VALUES OF ISTATE ARE AS FOLLOWS.
C          0  MEANS THIS IS THE FIRST CALL FOR THE PROBLEM, AND
C             LSOIBT IS TO COMPUTE THE INITIAL VALUE OF DY/DT
C             (WHILE DOING OTHER INITIALIZATIONS).  SEE NOTE BELOW.
C          1  MEANS THIS IS THE FIRST CALL FOR THE PROBLEM, AND
C             THE INITIAL VALUE OF DY/DT HAS BEEN SUPPLIED IN
C             YDOTI (LSOIBT WILL DO OTHER INITIALIZATIONS). SEE NOTE
C             BELOW.
C          2  MEANS THIS IS NOT THE FIRST CALL, AND THE CALCULATION
C             IS TO CONTINUE NORMALLY, WITH NO CHANGE IN ANY INPUT
C             PARAMETERS EXCEPT POSSIBLY TOUT AND ITASK.
C             (IF ITOL, RTOL, AND/OR ATOL ARE CHANGED BETWEEN CALLS
C             WITH ISTATE = 2, THE NEW VALUES WILL BE USED BUT NOT
C             TESTED FOR LEGALITY.)
C          3  MEANS THIS IS NOT THE FIRST CALL, AND THE
C             CALCULATION IS TO CONTINUE NORMALLY, BUT WITH 
C             A CHANGE IN INPUT PARAMETERS OTHER THAN
C             TOUT AND ITASK.  CHANGES ARE ALLOWED IN
C             NEQ, ITOL, RTOL, ATOL, IOPT, LRW, LIW, MF, MB, NB,
C             AND ANY OF THE OPTIONAL INPUTS EXCEPT H0.
C             (SEE IWORK DESCRIPTION FOR MB AND NB.)
C          NOTE..  A PRELIMINARY CALL WITH TOUT = T IS NOT COUNTED
C          AS A FIRST CALL HERE, AS NO INITIALIZATION OR CHECKING OF
C          INPUT IS DONE.  (SUCH A CALL IS SOMETIMES USEFUL FOR THE
C          PURPOSE OF OUTPUTTING THE INITIAL CONDITIONS.)
C          THUS THE FIRST CALL FOR WHICH TOUT .NE. T REQUIRES
C          ISTATE = 0 OR 1 ON INPUT.
C
C          ON OUTPUT, ISTATE HAS THE FOLLOWING VALUES AND MEANINGS.
C           0 OR 1  MEANS NOTHING WAS DONE, AS TOUT WAS EQUAL TO T WITH
C              ISTATE = 0 OR 1 ON INPUT.  (HOWEVER, AN INTERNAL COUNTER
C              WAS SET TO DETECT AND PREVENT REPEATED CALLS OF THIS
C              TYPE. )
C           2  MEANS THAT THE INTEGRATION WAS PERFORMED SUCCESSFULLY. 
C           3  MEANS THAT THE USER-SUPPLIED SUBROUTINE RES SIGNALLED
C              LSOIBT TO HALT THE INTEGRATION AND RETURN (IRES=2).
C              INTEGRATION AS FAR AS T WAS ACHIEVED WITH NO OCCURRENCE
C              OF IRES=2, BUT THIS FLAG WAS SET ON ATTEMPTING THE NEXT
C              STEP.
C          -1  MEANS AN EXCESSIVE AMOUNT OF WORK (MORE THAN MXSTEP
C              STEPS) WAS DONE ON THIS CALL, BEFORE COMPLETING THE
C              REQUESTED TASK, BUT THE INTEGRATION WAS OTHERWISE
C              SUCCESSFUL AS FAR AS T.  (MXSTEP IS AN OPTIONAL INPUT
C              AND IS NORMALLY 500.)  TO CONTINUE, THE USER MAY
C              SIMPLY RESET ISTATE TO A VALUE .GT. 1 AND CALL AGAIN
C              (THE EXCESS WORK STEP COUNTER WILL BE RESET TO 0).
C              IN ADDITION, THE USER MAY INCREASE MXSTEP TO AVOID
C              THIS ERROR RETURN (SEE BELOW ON OPTIONAL INPUTS).
C          -2  MEANS TOO MUCH ACCURACY WAS REQUESTED FOR THE PRECISION
C              OF THE MACHINE BEING USED.  THIS WAS DETECTED BEFORE
C              COMPLETING THE REQUESTED TASK, BUT THE INTEGRATION
C              WAS SUCCESSFUL AS FAR AS T.  TO CONTINUE, THE TOLERANCE
C              PARAMETERS MUST BE RESET, AND ISTATE MUST BE SET
C              TO 3.  THE OPTIONAL OUTPUT TOLSF MAY BE USED FOR THIS
C              PURPOSE.  (NOTE.. IF THIS CONDITION IS DETECTED BEFORE 
C              TAKING ANY STEPS, THEN AN ILLEGAL INPUT RETURN
C              (ISTATE = -3) OCCURS INSTEAD.)
C          -3  MEANS ILLEGAL INPUT WAS DETECTED, BEFORE TAKING ANY
C              INTEGRATION STEPS.  SEE WRITTEN MESSAGE FOR DETAILS.
C              NOTE..  IF THE SOLVER DETECTS AN INFINITE LOOP OF CALLS
C              TO THE SOLVER WITH ILLEGAL INPUT, IT WILL CAUSE
C              THE RUN TO STOP.
C          -4  MEANS THERE WERE REPEATED ERROR TEST FAILURES ON
C              ONE ATTEMPTED STEP, BEFORE COMPLETING THE REQUESTED
C              TASK, BUT THE INTEGRATION WAS SUCCESSFUL AS FAR AS T.
C              THE PROBLEM MAY HAVE A SINGULARITY, OR THE INPUT
C              MAY BE INAPPROPRIATE.
C          -5  MEANS THERE WERE REPEATED CONVERGENCE TEST FAILURES ON 
C              ONE ATTEMPTED STEP, BEFORE COMPLETING THE REQUESTED
C              TASK, BUT THE INTEGRATION WAS SUCCESSFUL AS FAR AS T.
C              THIS MAY BE CAUSED BY AN INACCURATE JACOBIAN MATRIX.
C          -6  MEANS EWT(I) BECAME ZERO FOR SOME I DURING THE
C              INTEGRATION.  PURE RELATIVE ERROR CONTROL (ATOL(I)=0.0)
C              WAS REQUESTED ON A VARIABLE WHICH HAS NOW VANISHED.
C              THE INTEGRATION WAS SUCCESSFUL AS FAR AS T.
C          -7  MEANS THAT THE USER-SUPPLIED SUBROUTINE RES SET
C              ITS ERROR FLAG (IRES=3) DESPITE REPEATED TRIES BY LSOIBT
C              TO AVOID THAT CONDITION. 
C          -8  MEANS THAT ISTATE WAS 0 ON INPUT BUT LSOIBT WAS UNABLE 
C              TO COMPUTE THE INITIAL VALUE OF DY/DT.  SEE THE
C              PRINTED MESSAGE FOR DETAILS.
C
C          NOTE..  SINCE THE NORMAL OUTPUT VALUE OF ISTATE IS 2,
C          IT DOES NOT NEED TO BE RESET FOR NORMAL CONTINUATION.
C          SIMILARLY, ISTATE NEED NOT BE RESET IF RES TOLD LSOIBT
C          TO RETURN BECAUSE THE CALLING PROGRAM MUST CHANGE
C          THE PARAMETERS OF THE PROBLEM.
C          ALSO, SINCE A NEGATIVE INPUT VALUE OF ISTATE WILL BE
C          REGARDED AS ILLEGAL, A NEGATIVE OUTPUT VALUE REQUIRES THE
C          USER TO CHANGE IT, AND POSSIBLY OTHER INPUTS, BEFORE
C          CALLING THE SOLVER AGAIN.
C
C IOPT   = AN INTEGER FLAG TO SPECIFY WHETHER OR NOT ANY OPTIONAL
C          INPUTS ARE BEING USED ON THIS CALL.  INPUT ONLY. 
C          THE OPTIONAL INPUTS ARE LISTED SEPARATELY BELOW. 
C          IOPT = 0 MEANS NO OPTIONAL INPUTS ARE BEING USED.
C                   DEFAULT VALUES WILL BE USED IN ALL CASES.
C          IOPT = 1 MEANS ONE OR MORE OPTIONAL INPUTS ARE BEING USED. 
C
C RWORK  = A REAL WORKING ARRAY (DOUBLE PRECISION).
C          THE LENGTH OF RWORK MUST BE AT LEAST
C             20 + NYH*(MAXORD + 1) + 3*NEQ + LENWM    WHERE
C          NYH    = THE INITIAL VALUE OF NEQ,
C          MAXORD = 12 (IF METH = 1) OR 5 (IF METH = 2) (UNLESS A
C                   SMALLER VALUE IS GIVEN AS AN OPTIONAL INPUT),
C          LENWM  = 3*MB*MB*NB + 2.
C          (SEE MF DESCRIPTION FOR THE DEFINITION OF METH.) 
C          THUS IF MAXORD HAS ITS DEFAULT VALUE AND NEQ IS CONSTANT,
C          THIS LENGTH IS
C             22 + 16*NEQ + 3*MB*MB*NB     FOR MF = 11 OR 12,
C             22 + 9*NEQ + 3*MB*MB*NB      FOR MF = 21 OR 22.
C          THE FIRST 20 WORDS OF RWORK ARE RESERVED FOR CONDITIONAL
C          AND OPTIONAL INPUTS AND OPTIONAL OUTPUTS.
C
C          THE FOLLOWING WORD IN RWORK IS A CONDITIONAL INPUT..
C            RWORK(1) = TCRIT = CRITICAL VALUE OF T WHICH THE SOLVER
C                       IS NOT TO OVERSHOOT.  REQUIRED IF ITASK IS
C                       4 OR 5, AND IGNORED OTHERWISE.  (SEE ITASK.)
C
C LRW    = THE LENGTH OF THE ARRAY RWORK, AS DECLARED BY THE USER.
C          (THIS WILL BE CHECKED BY THE SOLVER.)
C
C IWORK  = AN INTEGER WORK ARRAY.  THE LENGTH OF IWORK MUST BE AT LEAST
C          20 + NEQ .  THE FIRST FEW WORDS OF IWORK ARE USED FOR
C          ADDITIONAL AND OPTIONAL INPUTS AND OPTIONAL OUTPUTS.
C
C          THE FOLLOWING 2 WORDS IN IWORK ARE ADDITIONAL REQUIRED
C          INPUTS TO LSOIBT.. 
C            IWORK(1) = MB = BLOCK SIZE 
C            IWORK(2) = NB = NUMBER OF BLOCKS IN THE MAIN DIAGONAL
C          THESE MUST SATISFY  MB .GE. 1, NB .GE. 4, AND MB*NB = NEQ. 
C
C LIW    = THE LENGTH OF THE ARRAY IWORK, AS DECLARED BY THE USER.
C          (THIS WILL BE CHECKED BY THE SOLVER.)
C
C NOTE..  THE WORK ARRAYS MUST NOT BE ALTERED BETWEEN CALLS TO LSOIBT 
C FOR THE SAME PROBLEM, EXCEPT POSSIBLY FOR THE ADDITIONAL AND
C OPTIONAL INPUTS, AND EXCEPT FOR THE LAST 3*NEQ WORDS OF RWORK.
C THE LATTER SPACE IS USED FOR INTERNAL SCRATCH SPACE, AND SO IS
C AVAILABLE FOR USE BY THE USER OUTSIDE LSOIBT BETWEEN CALLS, IF
C DESIRED (BUT NOT FOR USE BY RES, ADDA, OR JAC). 
C
C MF     = THE METHOD FLAG.  USED ONLY FOR INPUT.  THE LEGAL VALUES OF
C          MF ARE 11, 12, 21, AND 22.
C          MF HAS DECIMAL DIGITS METH AND MITER.. MF = 10*METH + MITER.
C            METH INDICATES THE BASIC LINEAR MULTISTEP METHOD..
C              METH = 1 MEANS THE IMPLICIT ADAMS METHOD.
C              METH = 2 MEANS THE METHOD BASED ON BACKWARD
C                       DIFFERENTIATION FORMULAS (BDF-S).
C                THE BDF METHOD IS STRONGLY PREFERRED FOR STIFF PROB- 
C              LEMS, WHILE THE ADAMS METHOD IS PREFERRED WHEN THE PROB-
C              LEM IS NOT STIFF. IF THE MATRIX A(T,Y) IS NONSINGULAR, 
C              STIFFNESS HERE CAN BE TAKEN TO MEAN THAT OF THE EXPLICIT
C              ODE SYSTEM DY/DT = A**(-1) * G.  IF A IS SINGULAR, THE 
C              CONCEPT OF STIFFNESS IS NOT WELL DEFINED.
C                IF YOU DO NOT KNOW WHETHER THE PROBLEM IS STIFF, WE
C              RECOMMEND USING METH = 2.  IF IT IS STIFF, THE ADVAN-
C              TAGE OF METH = 2 OVER 1 WILL BE GREAT, WHILE IF IT IS
C              NOT STIFF, THE ADVANTAGE OF METH = 1 WILL BE SLIGHT.
C              IF MAXIMUM EFFICIENCY IS IMPORTANT, SOME EXPERIMENTATION
C              WITH METH MAY BE NECESSARY.
C            MITER INDICATES THE CORRECTOR ITERATION METHOD..
C              MITER = 1 MEANS CHORD ITERATION WITH A USER-SUPPLIED
C                        BLOCK-TRIDIAGONAL JACOBIAN.
C              MITER = 2 MEANS CHORD ITERATION WITH AN INTERNALLY
C                        GENERATED (DIFFERENCE QUOTIENT) BLOCK-
C                        TRIDIAGONAL JACOBIAN APPROXIMATION, USING
C                        3*MB+1 EXTRA CALLS TO RES PER DR/DY EVALUATION.
C              IF MITER = 1, THE USER MUST SUPPLY A SUBROUTINE
C              JAC (THE NAME IS ARBITRARY) AS DESCRIBED ABOVE UNDER JAC.
C              FOR MITER = 2, A DUMMY ARGUMENT CAN BE USED. 
C-----------------------------------------------------------------------
C OPTIONAL INPUTS.
C
C THE FOLLOWING IS A LIST OF THE OPTIONAL INPUTS PROVIDED FOR IN THE
C CALL SEQUENCE.  (SEE ALSO PART II.)  FOR EACH SUCH INPUT VARIABLE,
C THIS TABLE LISTS ITS NAME AS USED IN THIS DOCUMENTATION, ITS
C LOCATION IN THE CALL SEQUENCE, ITS MEANING, AND THE DEFAULT VALUE.
C THE USE OF ANY OF THESE INPUTS REQUIRES IOPT = 1, AND IN THAT
C CASE ALL OF THESE INPUTS ARE EXAMINED.  A VALUE OF ZERO FOR ANY
C OF THESE OPTIONAL INPUTS WILL CAUSE THE DEFAULT VALUE TO BE USED.
C THUS TO USE A SUBSET OF THE OPTIONAL INPUTS, SIMPLY PRELOAD
C LOCATIONS 5 TO 10 IN RWORK AND IWORK TO 0.0 AND 0 RESPECTIVELY, AND 
C THEN SET THOSE OF INTEREST TO NONZERO VALUES.
C
C NAME    LOCATION      MEANING AND DEFAULT VALUE 
C
C H0      RWORK(5)  THE STEP SIZE TO BE ATTEMPTED ON THE FIRST STEP.
C                   THE DEFAULT VALUE IS DETERMINED BY THE SOLVER.
C
C HMAX    RWORK(6)  THE MAXIMUM ABSOLUTE STEP SIZE ALLOWED. 
C                   THE DEFAULT VALUE IS INFINITE.
C
C HMIN    RWORK(7)  THE MINIMUM ABSOLUTE STEP SIZE ALLOWED. 
C                   THE DEFAULT VALUE IS 0.  (THIS LOWER BOUND IS NOT 
C                   ENFORCED ON THE FINAL STEP BEFORE REACHING TCRIT
C                   WHEN ITASK = 4 OR 5.)
C
C MAXORD  IWORK(5)  THE MAXIMUM ORDER TO BE ALLOWED.  THE DEFAULT
C                   VALUE IS 12 IF METH = 1, AND 5 IF METH = 2.
C                   IF MAXORD EXCEEDS THE DEFAULT VALUE, IT WILL
C                   BE REDUCED TO THE DEFAULT VALUE.
C                   IF MAXORD IS CHANGED DURING THE PROBLEM, IT MAY
C                   CAUSE THE CURRENT ORDER TO BE REDUCED.
C
C MXSTEP  IWORK(6)  MAXIMUM NUMBER OF (INTERNALLY DEFINED) STEPS
C                   ALLOWED DURING ONE CALL TO THE SOLVER.
C                   THE DEFAULT VALUE IS 500.
C
C MXHNIL  IWORK(7)  MAXIMUM NUMBER OF MESSAGES PRINTED (PER PROBLEM)
C                   WARNING THAT T + H = T ON A STEP (H = STEP SIZE). 
C                   THIS MUST BE POSITIVE TO RESULT IN A NON-DEFAULT
C                   VALUE.  THE DEFAULT VALUE IS 10.
C-----------------------------------------------------------------------
C OPTIONAL OUTPUTS. 
C
C AS OPTIONAL ADDITIONAL OUTPUT FROM LSOIBT, THE VARIABLES LISTED
C BELOW ARE QUANTITIES RELATED TO THE PERFORMANCE OF LSOIBT 
C WHICH ARE AVAILABLE TO THE USER.  THESE ARE COMMUNICATED BY WAY OF
C THE WORK ARRAYS, BUT ALSO HAVE INTERNAL MNEMONIC NAMES AS SHOWN.
C EXCEPT WHERE STATED OTHERWISE, ALL OF THESE OUTPUTS ARE DEFINED
C ON ANY SUCCESSFUL RETURN FROM LSOIBT, AND ON ANY RETURN WITH
C ISTATE = -1, -2, -4, -5, -6, OR -7. ON A RETURN WITH -3 (ILLEGAL
C INPUT) OR -8, THEY WILL BE UNCHANGED FROM THEIR EXISTING VALUES
C (IF ANY), EXCEPT POSSIBLY FOR TOLSF, LENRW, AND LENIW.
C ON ANY ERROR RETURN, OUTPUTS RELEVANT TO THE ERROR WILL BE DEFINED, 
C AS NOTED BELOW.
C
C NAME    LOCATION      MEANING
C
C HU      RWORK(11) THE STEP SIZE IN T LAST USED (SUCCESSFULLY).
C
C HCUR    RWORK(12) THE STEP SIZE TO BE ATTEMPTED ON THE NEXT STEP.
C
C TCUR    RWORK(13) THE CURRENT VALUE OF THE INDEPENDENT VARIABLE
C                   WHICH THE SOLVER HAS ACTUALLY REACHED, I.E. THE
C                   CURRENT INTERNAL MESH POINT IN T.  ON OUTPUT, TCUR
C                   WILL ALWAYS BE AT LEAST AS FAR AS THE ARGUMENT
C                   T, BUT MAY BE FARTHER (IF INTERPOLATION WAS DONE).
C
C TOLSF   RWORK(14) A TOLERANCE SCALE FACTOR, GREATER THAN 1.0,
C                   COMPUTED WHEN A REQUEST FOR TOO MUCH ACCURACY WAS 
C                   DETECTED (ISTATE = -3 IF DETECTED AT THE START OF 
C                   THE PROBLEM, ISTATE = -2 OTHERWISE).  IF ITOL IS
C                   LEFT UNALTERED BUT RTOL AND ATOL ARE UNIFORMLY
C                   SCALED UP BY A FACTOR OF TOLSF FOR THE NEXT CALL, 
C                   THEN THE SOLVER IS DEEMED LIKELY TO SUCCEED.
C                   (THE USER MAY ALSO IGNORE TOLSF AND ALTER THE
C                   TOLERANCE PARAMETERS IN ANY OTHER WAY APPROPRIATE.)
C
C NST     IWORK(11) THE NUMBER OF STEPS TAKEN FOR THE PROBLEM SO FAR. 
C
C NRE     IWORK(12) THE NUMBER OF RESIDUAL EVALUATIONS (RES CALLS)
C                   FOR THE PROBLEM SO FAR.
C
C NJE     IWORK(13) THE NUMBER OF JACOBIAN EVALUATIONS (EACH INVOLVING
C                   AN EVALUATION OF A AND DR/DY) FOR THE PROBLEM SO
C                   FAR.  THIS EQUALS THE NUMBER OF CALLS TO ADDA AND 
C                   (IF MITER = 1) TO JAC, AND THE NUMBER OF MATRIX
C                   L-U DECOMPOSITIONS. 
C
C NQU     IWORK(14) THE METHOD ORDER LAST USED (SUCCESSFULLY).
C
C NQCUR   IWORK(15) THE ORDER TO BE ATTEMPTED ON THE NEXT STEP.
C
C IMXER   IWORK(16) THE INDEX OF THE COMPONENT OF LARGEST MAGNITUDE IN
C                   THE WEIGHTED LOCAL ERROR VECTOR ( E(I)/EWT(I) ),
C                   ON AN ERROR RETURN WITH ISTATE = -4 OR -5.
C
C LENRW   IWORK(17) THE LENGTH OF RWORK ACTUALLY REQUIRED.
C                   THIS IS DEFINED ON NORMAL RETURNS AND ON AN ILLEGAL
C                   INPUT RETURN FOR INSUFFICIENT STORAGE.
C
C LENIW   IWORK(18) THE LENGTH OF IWORK ACTUALLY REQUIRED.
C                   THIS IS DEFINED ON NORMAL RETURNS AND ON AN ILLEGAL
C                   INPUT RETURN FOR INSUFFICIENT STORAGE.
C
C
C THE FOLLOWING TWO ARRAYS ARE SEGMENTS OF THE RWORK ARRAY WHICH
C MAY ALSO BE OF INTEREST TO THE USER AS OPTIONAL OUTPUTS.
C FOR EACH ARRAY, THE TABLE BELOW GIVES ITS INTERNAL NAME,
C ITS BASE ADDRESS IN RWORK, AND ITS DESCRIPTION. 
C
C NAME    BASE ADDRESS      DESCRIPTION 
C
C YH      21             THE NORDSIECK HISTORY ARRAY, OF SIZE NYH BY
C                        (NQCUR + 1), WHERE NYH IS THE INITIAL VALUE
C                        OF NEQ.  FOR J = 0,1,...,NQCUR, COLUMN J+1
C                        OF YH CONTAINS HCUR**J/FACTORIAL(J) TIMES
C                        THE J-TH DERIVATIVE OF THE INTERPOLATING
C                        POLYNOMIAL CURRENTLY REPRESENTING THE SOLUTION,
C                        EVALUATED AT T = TCUR.
C
C ACOR     LENRW-NEQ+1   ARRAY OF SIZE NEQ USED FOR THE ACCUMULATED
C                        CORRECTIONS ON EACH STEP, SCALED ON OUTPUT TO
C                        REPRESENT THE ESTIMATED LOCAL ERROR IN Y ON THE
C                        LAST STEP. THIS IS THE VECTOR E IN THE DESCRIP-
C                        TION OF THE ERROR CONTROL.  IT IS DEFINED ONLY
C                        ON A RETURN FROM LSOIBT WITH ISTATE = 2.
C
C-----------------------------------------------------------------------
C PART II.  OTHER ROUTINES CALLABLE.
C
C THE FOLLOWING ARE OPTIONAL CALLS WHICH THE USER MAY MAKE TO
C GAIN ADDITIONAL CAPABILITIES IN CONJUNCTION WITH LSOIBT.
C (THE ROUTINES XSETUN AND XSETF ARE DESIGNED TO CONFORM TO THE
C SLATEC ERROR HANDLING PACKAGE.)
C
C     FORM OF CALL                  FUNCTION
C   CALL XSETUN(LUN)          SET THE LOGICAL UNIT NUMBER, LUN, FOR
C                             OUTPUT OF MESSAGES FROM LSOIBT, IF
C                             THE DEFAULT IS NOT DESIRED.
C                             THE DEFAULT VALUE OF LUN IS 6.
C
C   CALL XSETF(MFLAG)         SET A FLAG TO CONTROL THE PRINTING OF
C                             MESSAGES BY LSOIBT. 
C                             MFLAG = 0 MEANS DO NOT PRINT. (DANGER.. 
C                             THIS RISKS LOSING VALUABLE INFORMATION.)
C                             MFLAG = 1 MEANS PRINT (THE DEFAULT).
C
C                             EITHER OF THE ABOVE CALLS MAY BE MADE AT
C                             ANY TIME AND WILL TAKE EFFECT IMMEDIATELY.
C
C   CALL SRCOM(RSAV,ISAV,JOB) SAVES AND RESTORES THE CONTENTS OF
C                             THE INTERNAL COMMON BLOCKS USED BY
C                             LSOIBT (SEE PART III BELOW).
C                             RSAV MUST BE A REAL ARRAY OF LENGTH 218 
C                             OR MORE, AND ISAV MUST BE AN INTEGER
C                             ARRAY OF LENGTH 41 OR MORE.
C                             JOB=1 MEANS SAVE COMMON INTO RSAV/ISAV. 
C                             JOB=2 MEANS RESTORE COMMON FROM RSAV/ISAV.
C                                SRCOM IS USEFUL IF ONE IS
C                             INTERRUPTING A RUN AND RESTARTING
C                             LATER, OR ALTERNATING BETWEEN TWO OR
C                             MORE PROBLEMS SOLVED WITH LSOIBT.
C
C   CALL INTDY(,,,,,)         PROVIDE DERIVATIVES OF Y, OF VARIOUS
C        (SEE BELOW)          ORDERS, AT A SPECIFIED POINT T, IF
C                             DESIRED.  IT MAY BE CALLED ONLY AFTER
C                             A SUCCESSFUL RETURN FROM LSOIBT.
C
C THE DETAILED INSTRUCTIONS FOR USING INTDY ARE AS FOLLOWS. 
C THE FORM OF THE CALL IS..
C
C   CALL INTDY (T, K, RWORK(21), NYH, DKY, IFLAG) 
C
C THE INPUT PARAMETERS ARE..
C
C T         = VALUE OF INDEPENDENT VARIABLE WHERE ANSWERS ARE DESIRED 
C             (NORMALLY THE SAME AS THE T LAST RETURNED BY LSOIBT).
C             FOR VALID RESULTS, T MUST LIE BETWEEN TCUR - HU AND TCUR.
C             (SEE OPTIONAL OUTPUTS FOR TCUR AND HU.)
C K         = INTEGER ORDER OF THE DERIVATIVE DESIRED.  K MUST SATISFY
C             0 .LE. K .LE. NQCUR, WHERE NQCUR IS THE CURRENT ORDER
C             (SEE OPTIONAL OUTPUTS).  THE CAPABILITY CORRESPONDING
C             TO K = 0, I.E. COMPUTING Y(T), IS ALREADY PROVIDED
C             BY LSOIBT DIRECTLY.  SINCE NQCUR .GE. 1, THE FIRST
C             DERIVATIVE DY/DT IS ALWAYS AVAILABLE WITH INTDY.
C RWORK(21) = THE BASE ADDRESS OF THE HISTORY ARRAY YH.
C NYH       = COLUMN LENGTH OF YH, EQUAL TO THE INITIAL VALUE OF NEQ. 
C
C THE OUTPUT PARAMETERS ARE.. 
C
C DKY       = A REAL ARRAY OF LENGTH NEQ CONTAINING THE COMPUTED VALUE
C             OF THE K-TH DERIVATIVE OF Y(T).
C IFLAG     = INTEGER FLAG, RETURNED AS 0 IF K AND T WERE LEGAL,
C             -1 IF K WAS ILLEGAL, AND -2 IF T WAS ILLEGAL. 
C             ON AN ERROR RETURN, A MESSAGE IS ALSO WRITTEN.
C-----------------------------------------------------------------------
C PART III.  COMMON BLOCKS.
C
C IF LSOIBT IS TO BE USED IN AN OVERLAY SITUATION, THE USER 
C MUST DECLARE, IN THE PRIMARY OVERLAY, THE VARIABLES IN..
C   (1) THE CALL SEQUENCE TO LSOIBT,
C   (2) THE TWO INTERNAL COMMON BLOCKS
C         /LS0001/  OF LENGTH  257  (218 DOUBLE PRECISION WORDS
C                         FOLLOWED BY 39 INTEGER WORDS),
C         /EH0001/  OF LENGTH  2 (INTEGER WORDS). 
C
C IF LSOIBT IS USED ON A SYSTEM IN WHICH THE CONTENTS OF INTERNAL
C COMMON BLOCKS ARE NOT PRESERVED BETWEEN CALLS, THE USER SHOULD
C DECLARE THE ABOVE TWO COMMON BLOCKS IN HIS MAIN PROGRAM TO INSURE
C THAT THEIR CONTENTS ARE PRESERVED.
C
C IF THE SOLUTION OF A GIVEN PROBLEM BY LSOIBT IS TO BE INTERRUPTED
C AND THEN LATER CONTINUED, SUCH AS WHEN RESTARTING AN INTERRUPTED RUN
C OR ALTERNATING BETWEEN TWO OR MORE PROBLEMS, THE USER SHOULD SAVE,
C FOLLOWING THE RETURN FROM THE LAST LSOIBT CALL PRIOR TO THE
C INTERRUPTION, THE CONTENTS OF THE CALL SEQUENCE VARIABLES AND THE
C INTERNAL COMMON BLOCKS, AND LATER RESTORE THESE VALUES BEFORE THE
C NEXT LSOIBT CALL FOR THAT PROBLEM.  TO SAVE AND RESTORE THE COMMON
C BLOCKS, USE SUBROUTINE SRCOM (SEE PART II ABOVE).
C
C-----------------------------------------------------------------------
C PART IV.  OPTIONALLY REPLACEABLE SOLVER ROUTINES.
C
C BELOW ARE DESCRIPTIONS OF TWO ROUTINES IN THE LSOIBT PACKAGE WHICH
C RELATE TO THE MEASUREMENT OF ERRORS.  EITHER ROUTINE CAN BE
C REPLACED BY A USER-SUPPLIED VERSION, IF DESIRED.  HOWEVER, SINCE SUCH
C A REPLACEMENT MAY HAVE A MAJOR IMPACT ON PERFORMANCE, IT SHOULD BE
C DONE ONLY WHEN ABSOLUTELY NECESSARY, AND ONLY WITH GREAT CAUTION.
C (NOTE.. THE MEANS BY WHICH THE PACKAGE VERSION OF A ROUTINE IS
C SUPERSEDED BY THE USER-S VERSION MAY BE SYSTEM-DEPENDENT.)
C
C (A) EWSET.
C THE FOLLOWING SUBROUTINE IS CALLED JUST BEFORE EACH INTERNAL
C INTEGRATION STEP, AND SETS THE ARRAY OF ERROR WEIGHTS, EWT, AS
C DESCRIBED UNDER ITOL/RTOL/ATOL ABOVE..
C     SUBROUTINE EWSET (NEQ, ITOL, RTOL, ATOL, YCUR, EWT)
C WHERE NEQ, ITOL, RTOL, AND ATOL ARE AS IN THE LSOIBT CALL SEQUENCE, 
C YCUR CONTAINS THE CURRENT DEPENDENT VARIABLE VECTOR, AND
C EWT IS THE ARRAY OF WEIGHTS SET BY EWSET.
C
C IF THE USER SUPPLIES THIS SUBROUTINE, IT MUST RETURN IN EWT(I)
C (I = 1,...,NEQ) A POSITIVE QUANTITY SUITABLE FOR COMPARING ERRORS
C IN Y(I) TO.  THE EWT ARRAY RETURNED BY EWSET IS PASSED TO THE
C VNORM ROUTINE (SEE BELOW), AND ALSO USED BY LSOIBT IN THE COMPUTATION
C OF THE OPTIONAL OUTPUT IMXER, THE DIAGONAL JACOBIAN APPROXIMATION,
C AND THE INCREMENTS FOR DIFFERENCE QUOTIENT JACOBIANS.
C
C IN THE USER-SUPPLIED VERSION OF EWSET, IT MAY BE DESIRABLE TO USE
C THE CURRENT VALUES OF DERIVATIVES OF Y.  DERIVATIVES UP TO ORDER NQ 
C ARE AVAILABLE FROM THE HISTORY ARRAY YH, DESCRIBED ABOVE UNDER
C OPTIONAL OUTPUTS.  IN EWSET, YH IS IDENTICAL TO THE YCUR ARRAY,
C EXTENDED TO NQ + 1 COLUMNS WITH A COLUMN LENGTH OF NYH AND SCALE
C FACTORS OF H**J/FACTORIAL(J).  ON THE FIRST CALL FOR THE PROBLEM,
C GIVEN BY NST = 0, NQ IS 1 AND H IS TEMPORARILY SET TO 1.0.
C THE QUANTITIES NQ, NYH, H, AND NST CAN BE OBTAINED BY INCLUDING
C IN EWSET THE STATEMENTS..
C     DOUBLE PRECISION H, RLS 
C     COMMON /LS0001/ RLS(218),ILS(39)
C     NQ = ILS(35)
C     NYH = ILS(14) 
C     NST = ILS(36) 
C     H = RLS(212)
C THUS, FOR EXAMPLE, THE CURRENT VALUE OF DY/DT CAN BE OBTAINED AS
C YCUR(NYH+I)/H  (I=1,...,NEQ)  (AND THE DIVISION BY H IS
C UNNECESSARY WHEN NST = 0).
C
C (B) VNORM.
C THE FOLLOWING IS A REAL FUNCTION ROUTINE WHICH COMPUTES THE WEIGHTED
C ROOT-MEAN-SQUARE NORM OF A VECTOR V.. 
C     D = VNORM (N, V, W)
C WHERE.. 
C   N = THE LENGTH OF THE VECTOR,
C   V = REAL ARRAY OF LENGTH N CONTAINING THE VECTOR,
C   W = REAL ARRAY OF LENGTH N CONTAINING WEIGHTS,
C   D = SQRT( (1/N) * SUM(V(I)*W(I))**2 ).
C VNORM IS CALLED WITH N = NEQ AND WITH W(I) = 1.0/EWT(I), WHERE
C EWT IS AS SET BY SUBROUTINE EWSET.
C
C IF THE USER SUPPLIES THIS FUNCTION, IT SHOULD RETURN A NON-NEGATIVE 
C VALUE OF VNORM SUITABLE FOR USE IN THE ERROR CONTROL IN LSOIBT.
C NONE OF THE ARGUMENTS SHOULD BE ALTERED BY VNORM.
C FOR EXAMPLE, A USER-SUPPLIED VNORM ROUTINE MIGHT..
C   -SUBSTITUTE A MAX-NORM OF (V(I)*W(I)) FOR THE RMS-NORM, OR
C   -IGNORE SOME COMPONENTS OF V IN THE NORM, WITH THE EFFECT OF
C    SUPPRESSING THE ERROR CONTROL ON THOSE COMPONENTS OF Y.
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C OTHER ROUTINES IN THE LSOIBT PACKAGE. 
C
C IN ADDITION TO SUBROUTINE LSOIBT, THE LSOIBT PACKAGE INCLUDES THE
C FOLLOWING SUBROUTINES AND FUNCTION ROUTINES..
C  AIGBT    COMPUTES THE INITIAL VALUE OF THE VECTOR
C             DY/DT = INVERSE(A) * G
C  INTDY    COMPUTES AN INTERPOLATED VALUE OF THE Y VECTOR AT T = TOUT.
C  STODI    IS THE CORE INTEGRATOR, WHICH DOES ONE STEP OF THE
C           INTEGRATION AND THE ASSOCIATED ERROR CONTROL.
C  CFODE    SETS ALL METHOD COEFFICIENTS AND TEST CONSTANTS.
C  EWSET    SETS THE ERROR WEIGHT VECTOR EWT BEFORE EACH STEP.
C  VNORM    COMPUTES THE WEIGHTED R.M.S. NORM OF A VECTOR.
C  SRCOM    IS A USER-CALLABLE ROUTINE TO SAVE AND RESTORE
C           THE CONTENTS OF THE INTERNAL COMMON BLOCKS.
C  PJIBT    COMPUTES AND PREPROCESSES THE JACOBIAN MATRIX
C           AND THE NEWTON ITERATION MATRIX P.
C  SLSBT    MANAGES SOLUTION OF LINEAR SYSTEM IN CHORD ITERATION.
C  DECBT AND SOLBT   ARE ROUTINES FOR SOLVING BLOCK-TRIDIAGONAL
C           SYSTEMS OF LINEAR ALGEBRAIC EQUATIONS.
C  DGEFA AND DGESL   ARE ROUTINES FROM LINPACK FOR SOLVING FULL
C           SYSTEMS OF LINEAR ALGEBRAIC EQUATIONS.
C  DAXPY, DSCAL, IDAMAX, AND DDOT   ARE BASIC LINEAR ALGEBRA MODULES
C           (BLAS) USED BY THE ABOVE LINPACK ROUTINES.
C  D1MACH   COMPUTES THE UNIT ROUNDOFF IN A MACHINE-INDEPENDENT MANNER.
C  XERRWV, XSETUN, AND XSETF   HANDLE THE PRINTING OF ALL ERROR
C           MESSAGES AND WARNINGS.  XERRWV IS MACHINE-DEPENDENT.
C NOTE..  VNORM, IDAMAX, DDOT, AND D1MACH ARE FUNCTION ROUTINES.
C ALL THE OTHERS ARE SUBROUTINES.
C
C THE INTRINSIC AND EXTERNAL ROUTINES USED BY LSOIBT ARE.. DABS,
C DMAX1, DMIN1, DBLE, IABS, MAX0, MIN0, MOD, DSIGN, DSQRT, AND WRITE. 
C
C A BLOCK DATA SUBPROGRAM IS ALSO INCLUDED WITH THE PACKAGE,
C FOR LOADING SOME OF THE VARIABLES IN INTERNAL COMMON.
C
C-----------------------------------------------------------------------
C THE FOLLOWING CARD IS FOR OPTIMIZED COMPILATION ON LLNL COMPILERS.
CLLL. OPTIMIZE
C-----------------------------------------------------------------------
      EXTERNAL PJIBT, SLSBT
      INTEGER ILLIN, INIT, LYH, LEWT, LACOR, LSAVR, LWM, LIWM,
     1   MXSTEP, MXHNIL, NHNIL, NTREP, NSLAST, NYH, IOWNS
      INTEGER ICF, IERPJ, IERSL, JCUR, JSTART, KFLAG, L, METH, MITER, 
     1   MAXORD, MAXCOR, MSBP, MXNCF, N, NQ, NST, NRE, NJE, NQU
      INTEGER I, I1, I2, IER, IFLAG, IMXER, IRES, KGO,
     1   LENIW, LENRW, LENWM, LP, LYD0, MB, MORD, MXHNL0, MXSTP0, NB
      DOUBLE PRECISION ROWNS, 
     1   CCMAX, EL0, H, HMIN, HMXI, HU, RC, TN, UROUND
      DOUBLE PRECISION ATOLI, AYI, BIG, EWTI, H0, HMAX, HMX, RH, RTOLI,
     1   TCRIT, TDIST, TNEXT, TOL, TOLSF, TP, SIZE, SUM, W0,
     2   D1MACH, VNORM
      DIMENSION MORD(2)
      LOGICAL IHIT
C-----------------------------------------------------------------------
C THE FOLLOWING INTERNAL COMMON BLOCK CONTAINS
C (A) VARIABLES WHICH ARE LOCAL TO ANY SUBROUTINE BUT WHOSE VALUES MUST
C     BE PRESERVED BETWEEN CALLS TO THE ROUTINE (OWN VARIABLES), AND
C (B) VARIABLES WHICH ARE COMMUNICATED BETWEEN SUBROUTINES. 
C BLOCK LS0001 IS SHARED BY THE LSOIBT, LSODI, AND LSODE PACKAGES.
C THE STRUCTURE OF LS0001 IS AS FOLLOWS..  ALL REAL VARIABLES ARE
C LISTED FIRST, FOLLOWED BY ALL INTEGERS.  WITHIN EACH TYPE, THE
C VARIABLES ARE GROUPED WITH THOSE LOCAL TO SUBROUTINE LSOIBT FIRST,
C THEN THOSE LOCAL TO SUBROUTINE STODI, AND FINALLY THOSE USED
C FOR COMMUNICATION.  THE BLOCK IS DECLARED IN SUBROUTINES
C LSOIBT, INTDY, STODI, PJIBT, AND SLSBT.  GROUPS OF VARIABLES ARE
C REPLACED BY DUMMY ARRAYS IN THE COMMON DECLARATIONS IN ROUTINES
C WHERE THOSE VARIABLES ARE NOT USED.
C-----------------------------------------------------------------------
      COMMON /LS0001/ ROWNS(209),
     1   CCMAX, EL0, H, HMIN, HMXI, HU, RC, TN, UROUND,
     2   ILLIN, INIT, LYH, LEWT, LACOR, LSAVR, LWM, LIWM,
     3   MXSTEP, MXHNIL, NHNIL, NTREP, NSLAST, NYH, IOWNS(6),
     4   ICF, IERPJ, IERSL, JCUR, JSTART, KFLAG, L, METH, MITER,
     5   MAXORD, MAXCOR, MSBP, MXNCF, N, NQ, NST, NRE, NJE, NQU
C
      DATA  MORD(1),MORD(2)/12,5/, MXSTP0/500/, MXHNL0/10/
C-----------------------------------------------------------------------
C BLOCK A.
C THIS CODE BLOCK IS EXECUTED ON EVERY CALL.
C IT TESTS ISTATE AND ITASK FOR LEGALITY AND BRANCHES APPROPRIATELY.
C IF ISTATE .GT. 1 BUT THE FLAG INIT SHOWS THAT INITIALIZATION HAS
C NOT YET BEEN DONE, AN ERROR RETURN OCCURS.
C IF ISTATE = 0 OR 1 AND TOUT = T, JUMP TO BLOCK G AND RETURN
C IMMEDIATELY.
C-----------------------------------------------------------------------
      IF (ISTATE .LT. 0 .OR. ISTATE .GT. 3) GO TO 601
      IF (ITASK .LT. 1 .OR. ITASK .GT. 5) GO TO 602
      IF (ISTATE .LE. 1) GO TO 10
      IF (INIT .EQ. 0) GO TO 603
      IF (ISTATE .EQ. 2) GO TO 200
      GO TO 20
 10   INIT = 0
      IF (TOUT .EQ. T) GO TO 430
 20   NTREP = 0
C-----------------------------------------------------------------------
C BLOCK B.
C THE NEXT CODE BLOCK IS EXECUTED FOR THE INITIAL CALL (ISTATE = 0 OR 1)
C OR FOR A CONTINUATION CALL WITH PARAMETER CHANGES (ISTATE = 3).
C IT CONTAINS CHECKING OF ALL INPUTS AND VARIOUS INITIALIZATIONS.
C
C FIRST CHECK LEGALITY OF THE NON-OPTIONAL INPUTS NEQ, ITOL, IOPT,
C MF, MB, AND NB.
C-----------------------------------------------------------------------
      IF (NEQ(1) .LE. 0) GO TO 604
      IF (ISTATE .LE. 1) GO TO 25
      IF (NEQ(1) .GT. N) GO TO 605
 25   N = NEQ(1)
      IF (ITOL .LT. 1 .OR. ITOL .GT. 4) GO TO 606 
      IF (IOPT .LT. 0 .OR. IOPT .GT. 1) GO TO 607 
      METH = MF/10
      MITER = MF - 10*METH
      IF (METH .LT. 1 .OR. METH .GT. 2) GO TO 608 
      IF (MITER .LT. 1 .OR. MITER .GT. 2) GO TO 608
      MB = IWORK(1) 
      NB = IWORK(2) 
      IF (MB .LT. 1 .OR. MB .GT. N) GO TO 609
      IF (NB .LT. 4) GO TO 610
      IF (MB*NB .NE. N) GO TO 609
C NEXT PROCESS AND CHECK THE OPTIONAL INPUTS. --------------------------
      IF (IOPT .EQ. 1) GO TO 40
      MAXORD = MORD(METH)
      MXSTEP = MXSTP0
      MXHNIL = MXHNL0
      IF (ISTATE .LE. 1) H0 = 0.0D0
      HMXI = 0.0D0
      HMIN = 0.0D0
      GO TO 60
 40   MAXORD = IWORK(5)
      IF (MAXORD .LT. 0) GO TO 611
      IF (MAXORD .EQ. 0) MAXORD = 100
      MAXORD = MIN0(MAXORD,MORD(METH))
      MXSTEP = IWORK(6)
      IF (MXSTEP .LT. 0) GO TO 612
      IF (MXSTEP .EQ. 0) MXSTEP = MXSTP0
      MXHNIL = IWORK(7)
      IF (MXHNIL .LT. 0) GO TO 613
      IF (MXHNIL .EQ. 0) MXHNIL = MXHNL0
      IF (ISTATE .GT. 1) GO TO 50
      H0 = RWORK(5) 
      IF ((TOUT - T)*H0 .LT. 0.0D0) GO TO 614
 50   HMAX = RWORK(6)
      IF (HMAX .LT. 0.0D0) GO TO 615
      HMXI = 0.0D0
      IF (HMAX .GT. 0.0D0) HMXI = 1.0D0/HMAX
      HMIN = RWORK(7)
      IF (HMIN .LT. 0.0D0) GO TO 616
C-----------------------------------------------------------------------
C SET WORK ARRAY POINTERS AND CHECK LENGTHS LRW AND LIW.
C POINTERS TO SEGMENTS OF RWORK AND IWORK ARE NAMED BY PREFIXING L TO 
C THE NAME OF THE SEGMENT.  E.G., THE SEGMENT YH STARTS AT RWORK(LYH).
C SEGMENTS OF RWORK (IN ORDER) ARE DENOTED YH, WM, EWT, SAVR, ACOR.
C-----------------------------------------------------------------------
 60   LYH = 21
      IF (ISTATE .LE. 1) NYH = N
      LWM = LYH + (MAXORD + 1)*NYH
      LENWM = 3*MB*MB*NB + 2
      LEWT = LWM + LENWM
      LSAVR = LEWT + N
      LACOR = LSAVR + N
      LENRW = LACOR + N - 1
      IWORK(17) = LENRW
      LIWM = 1
      LENIW = 20 + N
      IWORK(18) = LENIW
      IF (LENRW .GT. LRW) GO TO 617
      IF (LENIW .GT. LIW) GO TO 618
C CHECK RTOL AND ATOL FOR LEGALITY. ------------------------------------
      RTOLI = RTOL(1)
      ATOLI = ATOL(1)
      DO 70 I = 1,N 
        IF (ITOL .GE. 3) RTOLI = RTOL(I)
        IF (ITOL .EQ. 2 .OR. ITOL .EQ. 4) ATOLI = ATOL(I)
        IF (RTOLI .LT. 0.0D0) GO TO 619 
        IF (ATOLI .LT. 0.0D0) GO TO 620 
 70     CONTINUE
      IF (ISTATE .LE. 1) GO TO 100
C IF ISTATE = 3, SET FLAG TO SIGNAL PARAMETER CHANGES TO STODI. --------
      JSTART = -1
      IF (NQ .LE. MAXORD) GO TO 90
C MAXORD WAS REDUCED BELOW NQ.  COPY YH(*,MAXORD+2) INTO YDOTI.---------
      DO 80 I = 1,N 
 80     YDOTI(I) = RWORK(I+LWM-1)
C RELOAD WM(1) = RWORK(LWM), SINCE LWM MAY HAVE CHANGED. ---------------
 90   RWORK(LWM) = DSQRT(UROUND)
      IF (N .EQ. NYH) GO TO 200
C NEQ WAS REDUCED.  ZERO PART OF YH TO AVOID UNDEFINED REFERENCES. -----
      I1 = LYH + L*NYH
      I2 = LYH + (MAXORD + 1)*NYH - 1
      IF (I1 .GT. I2) GO TO 200
      DO 95 I = I1,I2
 95     RWORK(I) = 0.0D0
      GO TO 200
C-----------------------------------------------------------------------
C BLOCK C.
C THE NEXT BLOCK IS FOR THE INITIAL CALL ONLY (ISTATE = 0 OR 1).
C IT CONTAINS ALL REMAINING INITIALIZATIONS, THE CALL TO AIGBT
C (IF ISTATE = 1), AND THE CALCULATION OF THE INITIAL STEP SIZE.
C THE ERROR WEIGHTS IN EWT ARE INVERTED AFTER BEING LOADED. 
C-----------------------------------------------------------------------
 100  UROUND = D1MACH(4)
      TN = T
      IF (ITASK .NE. 4 .AND. ITASK .NE. 5) GO TO 105
      TCRIT = RWORK(1)
      IF ((TCRIT - TOUT)*(TOUT - T) .LT. 0.0D0) GO TO 625
      IF (H0 .NE. 0.0D0 .AND. (T + H0 - TCRIT)*H0 .GT. 0.0D0)
     1   H0 = TCRIT - T
 105  JSTART = 0
      RWORK(LWM) = DSQRT(UROUND)
      NHNIL = 0
      NST = 0
      NRE = 0
      NJE = 0
      NSLAST = 0
      HU = 0.0D0
      NQU = 0
      CCMAX = 0.3D0 
      MAXCOR = 3
      MSBP = 20
      MXNCF = 10
C COMPUTE INITIAL DY/DT, IF NECESSARY, AND LOAD IT AND INITIAL Y INTO YH
      LYD0 = LYH + NYH
      LP = LWM + 1
      IF ( ISTATE .EQ. 1 )  GO TO 120
C LSOIBT MUST COMPUTE INITIAL DY/DT (LYD0 POINTS TO YH(*,2)). ----------
         CALL AIGBT( RES, ADDA, NEQ, T, Y, RWORK(LYD0),
     1               MB, NB, RWORK(LP), IWORK(21), IER )
         NRE = NRE + 1
         IF (IER)  560,110,565
  110    CONTINUE
         DO 115 I = 1,N
  115       RWORK(I+LYH-1) = Y(I)
         GO TO 130
C INITIAL DY/DT HAS BEEN SUPPLIED. -------------------------------------
  120    DO 125 I = 1,N
            RWORK(I+LYH-1) = Y(I)
  125       RWORK(I+LYD0-1) = YDOTI(I)
C LOAD AND INVERT THE EWT ARRAY.  (H IS TEMPORARILY SET TO 1.0.) -------
  130 CONTINUE
      NQ = 1
      H = 1.0D0
      CALL EWSET (N, ITOL, RTOL, ATOL, RWORK(LYH), RWORK(LEWT))
      DO 135 I = 1,N
        IF (RWORK(I+LEWT-1) .LE. 0.0D0) GO TO 621 
 135    RWORK(I+LEWT-1) = 1.0D0/RWORK(I+LEWT-1)
C-----------------------------------------------------------------------
C THE CODING BELOW COMPUTES THE STEP SIZE, H0, TO BE ATTEMPTED ON THE 
C FIRST STEP, UNLESS THE USER HAS SUPPLIED A VALUE FOR THIS.
C FIRST CHECK THAT TOUT - T DIFFERS SIGNIFICANTLY FROM ZERO.
C A SCALAR TOLERANCE QUANTITY TOL IS COMPUTED, AS MAX(RTOL(I))
C IF THIS IS POSITIVE, OR MAX(ATOL(I)/ABS(Y(I))) OTHERWISE, ADJUSTED
C SO AS TO BE BETWEEN 100*UROUND AND 1.0E-3.
C THEN THE COMPUTED VALUE H0 IS GIVEN BY..
C                                      NEQ
C   H0**2 = TOL / ( W0**-2 + (1/NEQ) * SUM ( YDOT(I)/YWT(I) )**2  )
C                                       1
C WHERE   W0      = MAX ( ABS(T), ABS(TOUT) ),
C         YDOT(I) = I-TH COMPONENT OF INITIAL VALUE OF DY/DT,
C         YWT(I)  = EWT(I)/TOL  (A WEIGHT FOR Y(I)).
C THE SIGN OF H0 IS INFERRED FROM THE INITIAL VALUES OF TOUT AND T.
C-----------------------------------------------------------------------
      IF (H0 .NE. 0.0D0) GO TO 180
      TDIST = DABS(TOUT - T)
      W0 = DMAX1(DABS(T),DABS(TOUT))
      IF (TDIST .LT. 2.0D0*UROUND*W0) GO TO 622
      TOL = RTOL(1) 
      IF (ITOL .LE. 2) GO TO 145
      DO 140 I = 1,N
 140    TOL = DMAX1(TOL,RTOL(I))
 145  IF (TOL .GT. 0.0D0) GO TO 160
      ATOLI = ATOL(1)
      DO 150 I = 1,N
        IF (ITOL .EQ. 2 .OR. ITOL .EQ. 4) ATOLI = ATOL(I)
        AYI = DABS(Y(I))
        IF (AYI .NE. 0.0D0) TOL = DMAX1(TOL,ATOLI/AYI)
 150    CONTINUE
 160  TOL = DMAX1(TOL,100.0D0*UROUND)
      TOL = DMIN1(TOL,0.001D0)
      SUM = VNORM (N, RWORK(LYD0), RWORK(LEWT))
      SUM = 1.0D0/(TOL*W0*W0) + TOL*SUM**2
      H0 = 1.0D0/DSQRT(SUM)
      H0 = DMIN1(H0,TDIST)
      H0 = DSIGN(H0,TOUT-T)
C ADJUST H0 IF NECESSARY TO MEET HMAX BOUND. ---------------------------
 180  RH = DABS(H0)*HMXI
      IF (RH .GT. 1.0D0) H0 = H0/RH
C LOAD H WITH H0 AND SCALE YH(*,2) BY H0. ------------------------------
      H = H0
      DO 190 I = 1,N
 190    RWORK(I+LYD0-1) = H0*RWORK(I+LYD0-1)
      GO TO 270
C-----------------------------------------------------------------------
C BLOCK D.
C THE NEXT CODE BLOCK IS FOR CONTINUATION CALLS ONLY (ISTATE = 2 OR 3)
C AND IS TO CHECK STOP CONDITIONS BEFORE TAKING A STEP.
C-----------------------------------------------------------------------
 200  NSLAST = NST
      GO TO (210, 250, 220, 230, 240), ITASK
 210  IF ((TN - TOUT)*H .LT. 0.0D0) GO TO 250
      CALL INTDY (TOUT, 0, RWORK(LYH), NYH, Y, IFLAG)
      IF (IFLAG .NE. 0) GO TO 627
      T = TOUT
      GO TO 420
 220  TP = TN - HU*(1.0D0 + 100.0D0*UROUND)
      IF ((TP - TOUT)*H .GT. 0.0D0) GO TO 623
      IF ((TN - TOUT)*H .LT. 0.0D0) GO TO 250
      GO TO 400
 230  TCRIT = RWORK(1)
      IF ((TN - TCRIT)*H .GT. 0.0D0) GO TO 624
      IF ((TCRIT - TOUT)*H .LT. 0.0D0) GO TO 625
      IF ((TN - TOUT)*H .LT. 0.0D0) GO TO 245
      CALL INTDY (TOUT, 0, RWORK(LYH), NYH, Y, IFLAG)
      IF (IFLAG .NE. 0) GO TO 627
      T = TOUT
      GO TO 420
 240  TCRIT = RWORK(1)
      IF ((TN - TCRIT)*H .GT. 0.0D0) GO TO 624
 245  HMX = DABS(TN) + DABS(H)
      IHIT = DABS(TN - TCRIT) .LE. 100.0D0*UROUND*HMX
      IF (IHIT) GO TO 400
      TNEXT = TN + H*(1.0D0 + 4.0D0*UROUND)
      IF ((TNEXT - TCRIT)*H .LE. 0.0D0) GO TO 250 
      H = (TCRIT - TN)*(1.0D0 - 4.0D0*UROUND)
      IF (ISTATE .EQ. 2) JSTART = -2
C-----------------------------------------------------------------------
C BLOCK E.
C THE NEXT BLOCK IS NORMALLY EXECUTED FOR ALL CALLS AND CONTAINS
C THE CALL TO THE ONE-STEP CORE INTEGRATOR STODI. 
C
C THIS IS A LOOPING POINT FOR THE INTEGRATION STEPS.
C
C FIRST CHECK FOR TOO MANY STEPS BEING TAKEN, UPDATE EWT (IF NOT AT
C START OF PROBLEM), CHECK FOR TOO MUCH ACCURACY BEING REQUESTED, AND 
C CHECK FOR H BELOW THE ROUNDOFF LEVEL IN T.
C-----------------------------------------------------------------------
 250  CONTINUE
      IF ((NST-NSLAST) .GE. MXSTEP) GO TO 500
      CALL EWSET (N, ITOL, RTOL, ATOL, RWORK(LYH), RWORK(LEWT))
      DO 260 I = 1,N
        IF (RWORK(I+LEWT-1) .LE. 0.0D0) GO TO 510 
 260    RWORK(I+LEWT-1) = 1.0D0/RWORK(I+LEWT-1)
 270  TOLSF = UROUND*VNORM (N, RWORK(LYH), RWORK(LEWT))
      IF (TOLSF .LE. 1.0D0) GO TO 280
      TOLSF = TOLSF*2.0D0
      IF (NST .EQ. 0) GO TO 626
      GO TO 520
 280  IF ((TN + H) .NE. TN) GO TO 290
      NHNIL = NHNIL + 1
      IF (NHNIL .GT. MXHNIL) GO TO 290
      CALL XERRWV(50HLSOIBT-- WARNING..INTERNAL T (=R1) AND H (=R2) ARE,
     1   50, 101, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(
     1  60H      SUCH THAT IN THE MACHINE, T + H = T ON THE NEXT STEP  ,
     1   60, 101, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      (H = STEP SIZE). SOLVER WILL CONTINUE ANYWAY,
     1   50, 101, 0, 0, 0, 0, 2, TN, H) 
      IF (NHNIL .LT. MXHNIL) GO TO 290
      CALL XERRWV(50HLSOIBT-- ABOVE WARNING HAS BEEN ISSUED I1 TIMES.  ,
     1   50, 102, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      IT WILL NOT BE ISSUED AGAIN FOR THIS PROBLEM,
     1   50, 102, 0, 1, MXHNIL, 0, 0, 0.0D0, 0.0D0)
 290  CONTINUE
C-----------------------------------------------------------------------
C     CALL STODI(NEQ,Y,YH,NYH,YH1,EWT,SAVF,SAVR,ACOR,WM,IWM,RES,
C                ADDA,JAC,PJIBT,SLSBT)
C NOTE... SAVF IN STODI OCCUPIES THE SAME SPACE AS YDOTI IN LSOIBT.
C-----------------------------------------------------------------------
      CALL STODI (NEQ, Y, RWORK(LYH), NYH, RWORK(LYH), RWORK(LEWT),
     1   YDOTI, RWORK(LSAVR), RWORK(LACOR), RWORK(LWM),
     2   IWORK(LIWM), RES, ADDA, JAC, PJIBT, SLSBT )
      KGO = 1 - KFLAG
      GO TO (300, 530, 540, 400, 550), KGO
C
C KGO = 1,SUCCESS. 2,ERROR TEST FAILURE. 3,CONVERGENCE FAILURE.
C       4,RES ORDERED RETURN. 5,RES RETURNED ERROR.
C-----------------------------------------------------------------------
C BLOCK F.
C THE FOLLOWING BLOCK HANDLES THE CASE OF A SUCCESSFUL RETURN FROM THE
C CORE INTEGRATOR (KFLAG = 0).  TEST FOR STOP CONDITIONS.
C-----------------------------------------------------------------------
 300  INIT = 1
      GO TO (310, 400, 330, 340, 350), ITASK
C ITASK = 1.  IF TOUT HAS BEEN REACHED, INTERPOLATE. -------------------
 310  IF ((TN - TOUT)*H .LT. 0.0D0) GO TO 250
      CALL INTDY (TOUT, 0, RWORK(LYH), NYH, Y, IFLAG)
      T = TOUT
      GO TO 420
C ITASK = 3.  JUMP TO EXIT IF TOUT WAS REACHED. ------------------------
 330  IF ((TN - TOUT)*H .GE. 0.0D0) GO TO 400
      GO TO 250
C ITASK = 4.  SEE IF TOUT OR TCRIT WAS REACHED.  ADJUST H IF NECESSARY.
 340  IF ((TN - TOUT)*H .LT. 0.0D0) GO TO 345
      CALL INTDY (TOUT, 0, RWORK(LYH), NYH, Y, IFLAG)
      T = TOUT
      GO TO 420
 345  HMX = DABS(TN) + DABS(H)
      IHIT = DABS(TN - TCRIT) .LE. 100.0D0*UROUND*HMX
      IF (IHIT) GO TO 400
      TNEXT = TN + H*(1.0D0 + 4.0D0*UROUND)
      IF ((TNEXT - TCRIT)*H .LE. 0.0D0) GO TO 250 
      H = (TCRIT - TN)*(1.0D0 - 4.0D0*UROUND)
      JSTART = -2
      GO TO 250
C ITASK = 5.  SEE IF TCRIT WAS REACHED AND JUMP TO EXIT. ---------------
 350  HMX = DABS(TN) + DABS(H)
      IHIT = DABS(TN - TCRIT) .LE. 100.0D0*UROUND*HMX
C-----------------------------------------------------------------------
C BLOCK G.
C THE FOLLOWING BLOCK HANDLES ALL SUCCESSFUL RETURNS FROM LSOIBT.
C IF ITASK .NE. 1, Y IS LOADED FROM YH AND T IS SET ACCORDINGLY.
C ISTATE IS SET TO 2, THE ILLEGAL INPUT COUNTER IS ZEROED, AND THE
C OPTIONAL OUTPUTS ARE LOADED INTO THE WORK ARRAYS BEFORE RETURNING.  IF
C ISTATE = 0 OR 1 AND TOUT = T, THERE IS A RETURN WITH NO ACTION TAKEN,
C EXCEPT THAT IF THIS HAS HAPPENED REPEATEDLY, THE RUN IS TERMINATED. 
C-----------------------------------------------------------------------
 400  DO 410 I = 1,N
 410    Y(I) = RWORK(I+LYH-1) 
      T = TN
      IF (ITASK .NE. 4 .AND. ITASK .NE. 5) GO TO 420
      IF (IHIT) T = TCRIT
  420 ISTATE = 2
      IF ( KFLAG .EQ. -3 )  ISTATE = 3
      ILLIN = 0
      RWORK(11) = HU
      RWORK(12) = H 
      RWORK(13) = TN
      IWORK(11) = NST
      IWORK(12) = NRE
      IWORK(13) = NJE
      IWORK(14) = NQU
      IWORK(15) = NQ
      RETURN
C
 430  NTREP = NTREP + 1
      IF (NTREP .LT. 5) RETURN
      CALL XERRWV(
     1  60HLSOIBT-- REPEATED CALLS WITH ISTATE= 0 OR 1 AND TOUT= T(=R1),
     1   60, 301, 0, 0, 0, 0, 1, T, 0.0D0)
      GO TO 800
C-----------------------------------------------------------------------
C BLOCK H.
C THE FOLLOWING BLOCK HANDLES ALL UNSUCCESSFUL RETURNS OTHER THAN
C THOSE FOR ILLEGAL INPUT.  FIRST THE ERROR MESSAGE ROUTINE IS CALLED.
C IF THERE WAS AN ERROR TEST OR CONVERGENCE TEST FAILURE, IMXER IS SET.
C THEN Y IS LOADED FROM YH, T IS SET TO TN, AND THE ILLEGAL INPUT
C COUNTER ILLIN IS SET TO 0.  THE OPTIONAL OUTPUTS ARE LOADED INTO
C THE WORK ARRAYS BEFORE RETURNING.
C-----------------------------------------------------------------------
C THE MAXIMUM NUMBER OF STEPS WAS TAKEN BEFORE REACHING TOUT. ----------
 500  CALL XERRWV(50HLSOIBT-- AT CURRENT T (=R1), MXSTEP (=I1) STEPS   ,
     1   50, 201, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      TAKEN ON THIS CALL BEFORE REACHING TOUT     ,
     1   50, 201, 0, 1, MXSTEP, 0, 1, TN, 0.0D0)
      ISTATE = -1
      GO TO 580
C EWT(I) .LE. 0.0 FOR SOME I (NOT AT START OF PROBLEM). ----------------
 510  EWTI = RWORK(LEWT+I-1)
      CALL XERRWV(50HLSOIBT-- AT T (=R1), EWT(I1) HAS BECOME R2 .LE. 0.,
     1   50, 202, 0, 1, I, 0, 2, TN, EWTI)
      ISTATE = -6
      GO TO 590
C TOO MUCH ACCURACY REQUESTED FOR MACHINE PRECISION. -------------------
 520  CALL XERRWV(50HLSOIBT-- AT T (=R1), TOO MUCH ACCURACY REQUESTED  ,
     1   50, 203, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      FOR PRECISION OF MACHINE..  SEE TOLSF (=R2) ,
     1   50, 203, 0, 0, 0, 0, 2, TN, TOLSF)
      RWORK(14) = TOLSF
      ISTATE = -2
      GO TO 590
C KFLAG = -1.  ERROR TEST FAILED REPEATEDLY OR WITH ABS(H) = HMIN. -----
 530  CALL XERRWV(50HLSOIBT-- AT T(=R1) AND STEP SIZE H(=R2), THE ERROR,
     1   50, 204, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      TEST FAILED REPEATEDLY OR WITH ABS(H) = HMIN,
     1   50, 204, 0, 0, 0, 0, 2, TN, H) 
      ISTATE = -4
      GO TO 570
C KFLAG = -2.  CONVERGENCE FAILED REPEATEDLY OR WITH ABS(H) = HMIN. ----
 540  CALL XERRWV(50HLSOIBT-- AT T (=R1) AND STEP SIZE H (=R2), THE    ,
     1   50, 205, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      CORRECTOR CONVERGENCE FAILED REPEATEDLY     ,
     1   50, 205, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(30H      OR WITH ABS(H) = HMIN   ,
     1   30, 205, 0, 0, 0, 0, 2, TN, H) 
      ISTATE = -5
      GO TO 570
C IRES = 3 RETURNED BY RES, DESPITE RETRIES BY STODI. ------------------
 550  CALL XERRWV(50HLSOIBT-- AT T (=R1) RESIDUAL ROUTINE RETURNED     ,
     1   50, 206, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(40H      ERROR IRES = 3 REPEATEDLY         ,
     1   40, 206, 0, 0, 0, 0, 1, TN, 0.0D0)
      ISTATE = -7
      GO TO 590
C AIGBT FAILED BECAUSE A DIAGONAL BLOCK OF A-MATRIX WAS SINGULAR. ------
 560  IER = -IER
      CALL XERRWV(
     1  60HLSOIBT-- ATTEMPT TO INITIALIZE DY/DT FAILED.. MATRIX A HAS A,
     1   60, 207, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      SINGULAR DIAGONAL BLOCK, BLOCK NO. = (I1)   ,
     2   50, 207, 0, 1, IER, 0, 0, 0.0D0, 0.0D0)
      ISTATE = -8
      RETURN
C AIGBT FAILED BECAUSE RES SET IRES TO 2 OR 3. -------------------------
 565  CALL XERRWV(50HLSOIBT-- ATTEMPT TO INITIALIZE DY/DT FAILED       ,
     1   50, 208, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      BECAUSE RESIDUAL ROUTINE SET ITS ERROR FLAG ,
     1   50, 208, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(20H      TO IRES = (I1),
     1   20, 208, 0, 1, IER, 0, 0, 0.0D0, 0.0D0)
      ISTATE = -8
      RETURN
C COMPUTE IMXER IF RELEVANT. -------------------------------------------
 570  BIG = 0.0D0
      IMXER = 1
      DO 575 I = 1,N
        SIZE = DABS(RWORK(I+LACOR-1)*RWORK(I+LEWT-1))
        IF (BIG .GE. SIZE) GO TO 575
        BIG = SIZE
        IMXER = I
 575    CONTINUE
      IWORK(16) = IMXER
C COMPUTE RESIDUAL IF RELEVANT. ----------------------------------------
 580  LYD0 = LYH + NYH
      DO 585 I = 1,N
         RWORK(I+LSAVR-1) = RWORK(I+LYD0-1)/H
 585     Y(I) = RWORK(I+LYH-1)
      IRES = 1
      CALL RES ( NEQ, TN, Y, RWORK(LSAVR), YDOTI, IRES )
      NRE = NRE + 1 
      IF ( IRES .LE. 1 )  GO TO 595
      CALL XERRWV(50HLSOIBT-- RESIDUAL ROUTINE SET ITS FLAG IRES       ,
     1   50, 210, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(50H      TO (I1) WHEN CALLED FOR FINAL OUTPUT.       ,
     1   50, 210, 0, 1, IRES, 0, 0, 0.0D0, 0.0D0) 
      GO TO 595
C SET Y VECTOR, T, ILLIN, AND OPTIONAL OUTPUTS. ------------------------
 590  DO 592 I = 1,N
 592    Y(I) = RWORK(I+LYH-1) 
 595  T = TN
      ILLIN = 0
      RWORK(11) = HU
      RWORK(12) = H 
      RWORK(13) = TN
      IWORK(11) = NST
      IWORK(12) = NRE
      IWORK(13) = NJE
      IWORK(14) = NQU
      IWORK(15) = NQ
      RETURN
C-----------------------------------------------------------------------
C BLOCK I.
C THE FOLLOWING BLOCK HANDLES ALL ERROR RETURNS DUE TO ILLEGAL INPUT
C (ISTATE = -3), AS DETECTED BEFORE CALLING THE CORE INTEGRATOR.
C FIRST THE ERROR MESSAGE ROUTINE IS CALLED.  THEN IF THERE HAVE BEEN 
C 5 CONSECUTIVE SUCH RETURNS JUST BEFORE THIS CALL TO THE SOLVER,
C THE RUN IS HALTED.
C-----------------------------------------------------------------------
 601  CALL XERRWV(30HLSOIBT-- ISTATE (=I1) ILLEGAL ,
     1   30, 1, 0, 1, ISTATE, 0, 0, 0.0D0, 0.0D0) 
      GO TO 700
 602  CALL XERRWV(30HLSOIBT-- ITASK (=I1) ILLEGAL  ,
     1   30, 2, 0, 1, ITASK, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 603  CALL XERRWV(50HLSOIBT-- ISTATE .GT. 1 BUT LSOIBT NOT INITIALIZED ,
     1   50, 3, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 604  CALL XERRWV(30HLSOIBT-- NEQ (=I1) .LT. 1     ,
     1   30, 4, 0, 1, NEQ(1), 0, 0, 0.0D0, 0.0D0) 
      GO TO 700
 605  CALL XERRWV(50HLSOIBT-- ISTATE = 3 AND NEQ INCREASED (I1 TO I2)  ,
     1   50, 5, 0, 2, N, NEQ(1), 0, 0.0D0, 0.0D0) 
      GO TO 700
 606  CALL XERRWV(30HLSOIBT-- ITOL (=I1) ILLEGAL   ,
     1   30, 6, 0, 1, ITOL, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 607  CALL XERRWV(30HLSOIBT-- IOPT (=I1) ILLEGAL   ,
     1   30, 7, 0, 1, IOPT, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 608  CALL XERRWV(30HLSOIBT-- MF (=I1) ILLEGAL     ,
     1   30, 8, 0, 1, MF, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 609  CALL XERRWV(40HLSOIBT-- MB (=I1) OR NB (=I2) ILLEGAL   ,
     1   50, 9, 0, 2, MB, NB, 0, 0.0D0, 0.0D0)
      GO TO 700
 610  CALL XERRWV(40HLSOIBT-- NB(=I1) ILLEGAL.. .LT. 4       ,
     1   50, 10, 0, 1, NB, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 611  CALL XERRWV(30HLSOIBT-- MAXORD (=I1) .LT. 0  ,
     1   30, 11, 0, 1, MAXORD, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 612  CALL XERRWV(30HLSOIBT-- MXSTEP (=I1) .LT. 0  ,
     1   30, 12, 0, 1, MXSTEP, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 613  CALL XERRWV(30HLSOIBT-- MXHNIL (=I1) .LT. 0  ,
     1   30, 13, 0, 1, MXHNIL, 0, 0, 0.0D0, 0.0D0)
      GO TO 700
 614  CALL XERRWV(40HLSOIBT-- TOUT (=R1) BEHIND T (=R2)      ,
     1   40, 14, 0, 0, 0, 0, 2, TOUT, T)
      CALL XERRWV(50H      INTEGRATION DIRECTION IS GIVEN BY H0 (=R1)  ,
     1   50, 14, 0, 0, 0, 0, 1, H0, 0.0D0)
      GO TO 700
 615  CALL XERRWV(30HLSOIBT-- HMAX (=R1) .LT. 0.0  ,
     1   30, 15, 0, 0, 0, 0, 1, HMAX, 0.0D0)
      GO TO 700
 616  CALL XERRWV(30HLSOIBT-- HMIN (=R1) .LT. 0.0  ,
     1   30, 16, 0, 0, 0, 0, 1, HMIN, 0.0D0)
      GO TO 700
 617  CALL XERRWV(
     1  60HLSOIBT-- RWORK LENGTH NEEDED, LENRW (=I1), EXCEEDS LRW (=I2),
     1   60, 17, 0, 2, LENRW, LRW, 0, 0.0D0, 0.0D0)
      GO TO 700
 618  CALL XERRWV(
     1  60HLSOIBT-- IWORK LENGTH NEEDED, LENIW (=I1), EXCEEDS LIW (=I2),
     1   60, 18, 0, 2, LENIW, LIW, 0, 0.0D0, 0.0D0)
      GO TO 700
 619  CALL XERRWV(40HLSOIBT-- RTOL(=I1) IS R1 .LT. 0.0       ,
     1   40, 19, 0, 1, I, 0, 1, RTOLI, 0.0D0)
      GO TO 700
 620  CALL XERRWV(40HLSOIBT-- ATOL(=I1) IS R1 .LT. 0.0       ,
     1   40, 20, 0, 1, I, 0, 1, ATOLI, 0.0D0)
      GO TO 700
 621  EWTI = RWORK(LEWT+I-1)
      CALL XERRWV(40HLSOIBT-- EWT(=I1) IS R1 .LE. 0.0        ,
     1   40, 21, 0, 1, I, 0, 1, EWTI, 0.0D0)
      GO TO 700
 622  CALL XERRWV(
     1  60HLSOIBT-- TOUT (=R1) TOO CLOSE TO T(=R2) TO START INTEGRATION,
     1   60, 22, 0, 0, 0, 0, 2, TOUT, T)
      GO TO 700
 623  CALL XERRWV(
     1  60HLSOIBT-- ITASK = I1 AND TOUT (=R1) BEHIND TCUR - HU (= R2)  ,
     1   60, 23, 0, 1, ITASK, 0, 2, TOUT, TP)
      GO TO 700
 624  CALL XERRWV(
     1  60HLSOIBT-- ITASK = 4 OR 5 AND TCRIT (=R1) BEHIND TCUR (=R2)   ,
     1   60, 24, 0, 0, 0, 0, 2, TCRIT, TN)
      GO TO 700
 625  CALL XERRWV(
     1  60HLSOIBT-- ITASK = 4 OR 5 AND TCRIT (=R1) BEHIND TOUT (=R2)   ,
     1   60, 25, 0, 0, 0, 0, 2, TCRIT, TOUT)
      GO TO 700
 626  CALL XERRWV(50HLSOIBT-- AT START OF PROBLEM, TOO MUCH ACCURACY   ,
     1   50, 26, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
      CALL XERRWV(
     1  60H      REQUESTED FOR PRECISION OF MACHINE..  SEE TOLSF (=R1) ,
     1   60, 26, 0, 0, 0, 0, 1, TOLSF, 0.0D0)
      RWORK(14) = TOLSF
      GO TO 700
 627  CALL XERRWV(50HLSOIBT-- TROUBLE FROM INTDY. ITASK = I1, TOUT = R1,
     1   50, 27, 0, 1, ITASK, 0, 1, TOUT, 0.0D0)
C
 700  IF (ILLIN .EQ. 5) GO TO 710
      ILLIN = ILLIN + 1
      ISTATE = -3
      RETURN
 710  CALL XERRWV(50HLSOIBT-- REPEATED OCCURRENCES OF ILLEGAL INPUT    ,
     1   50, 302, 0, 0, 0, 0, 0, 0.0D0, 0.0D0)
C
 800  CALL XERRWV(50HLSOIBT-- RUN ABORTED.. APPARENT INFINITE LOOP     ,
     1   50, 303, 2, 0, 0, 0, 0, 0.0D0, 0.0D0)
      RETURN
C----------------------- END OF SUBROUTINE LSOIBT ----------------------
      END 
